### ISSUE TITLE
python demo_toolbox.py 运行这个报错

### ISSUE THREAD

**Issue by tts2** [babysor/MockingBird#1015]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.
python demo_toolbox.py 运行这个报错
**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型
版本:master
系统:windows 10
python:canda
**Screenshots[截图（如有）]**
If applicable, add screenshots to help
![Uploading test.jpg…]()

**Comment by tts2** [comment]
(MockingBird) E:\sjy\python\Project\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "E:\sjy\python\Project\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from control.toolbox import Toolbox
  File "E:\sjy\python\Project\MockingBird-main\control\toolbox\__init__.py", line 1, in <module>
    from control.toolbox.ui import UI
  File "E:\sjy\python\Project\MockingBird-main\control\toolbox\ui.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\matplotlib\__init__.py", line 113, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\PIL\Image.py", line 68, in <module>
    from ._typing import StrOrBytesPath, TypeGuard
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\PIL\_typing.py", line 8, in <module>
    import numpy.typing as npt
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\numpy\typing\__init__.py", line 158, in <module>
    from numpy._typing import (
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\numpy\_typing\__init__.py", line 148, in <module>
    from ._scalars import (
  File "C:\Users\tts4\.conda\envs\MockingBird\lib\site-packages\numpy\_typing\_scalars.py", line 13, in <module>
    _UIntLike_co = Union[_BoolLike_co, np.unsignedinteger[Any]]
TypeError: 'type' object is not subscriptable

(MockingBird) E:\sjy\python\Project\MockingBird-main>

**Comment by tian412** [comment]
缺少依赖包
