### ISSUE TITLE
小白提问 图形界面出不来

### ISSUE THREAD

**Issue by braveboymy** [babysor/MockingBird#114]
(yuyi) F:\clonevoice\MockingBird>python demo_toolbox.py -d .\samples
Arguments:
    datasets_root:    samples
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "F:\clonevoice\MockingBird\toolbox\__init__.py", line 75, in __init__
    self.setup_events()
  File "F:\clonevoice\MockingBird\toolbox\__init__.py", line 112, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "F:\clonevoice\MockingBird\toolbox\ui.py", line 148, in setup_audio_devices
    for device in sd.query_devices():
  File "e:\ProgramData\Anaconda3\envs\yuyi\lib\site-packages\sounddevice.py", line 559, in query_devices
    return DeviceList(query_devices(i)
  File "e:\ProgramData\Anaconda3\envs\yuyi\lib\site-packages\sounddevice.py", line 559, in <genexpr>
    return DeviceList(query_devices(i)
  File "e:\ProgramData\Anaconda3\envs\yuyi\lib\site-packages\sounddevice.py", line 573, in query_devices
    name = name_bytes.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte

**Comment by babysor** [comment]
翻一下issue，有一个相关的
