### ISSUE TITLE
请问让程序能正常跑起来的步骤是怎样的？

### ISSUE THREAD

**Issue by yinjia823** [babysor/MockingBird#122]
2.1 使用数据集自己训练合成器模型（与2.2二选一）

·下载 数据集并解压：确保您可以访问 train 文件夹中的所有音频文件（如.wav）

·进行音频和梅尔频谱图预处理： python pre.py <datasets_root> 可以传入参数 --dataset {dataset} 支持 aidatatang_200zh, magicdata, aishell3
假如你下载的 aidatatang_200zh文件放在D盘，train文件路径为 D:\data\aidatatang_200zh\corpus\train , 你的datasets_root就是 D:\data\

·训练合成器： python synthesizer_train.py mandarin <datasets_root>/SV2TTS/synthesizer
当您在训练文件夹 synthesizer/saved_models/ 中看到注意线显示和损失满足您的需要时，请转到启动程序一步。

**是必须要完成上面所有的步骤才能跑起来么？才能到QT5的界面么？
感谢您的回复，谢谢！**

**Comment by LxKxC** [comment]
> aidatatang_200zh

先训练一个吧，把aidatatang_200zh训练十几万再考虑换别的

**Comment by LxKxC** [comment]
> 我在mac上使用MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)，上传台湾录音的时候，界面显示没有权限怎么办？

我没有macbook，但是mac os 应该是类linux的，我觉得这应该是你下载下来的文件夹权限错误导致的，你可以试试给整个项目文件夹赋777权限

**Comment by SkyChow7** [comment]
> > 我在mac上使用MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)，上传台湾录音的时候，界面显示没有权限怎么办？
> 
> 我没有macbook，但是mac os 应该是类linux的，我觉得这应该是你下载下来的文件夹权限错误导致的，你可以试试给整个项目文件夹赋777权限

我使用命令 sudo  chmod -R 777 MockingBird-main没起作用

**Comment by lyqscmy** [comment]
只用于预测的容器镜像我已经构建好，内置预训练模型，本次测试跑过了。
docker run -p 8080:8080 -it jiada/mocking_bird

**Comment by babysor** [comment]
> 只用于预测的容器镜像我已经构建好，内置预训练模型，本次测试跑过了。 docker run -p 8080:8080 -it jiada/mocking_bird

只有web界面吗？

**Comment by skygongque** [comment]
做了一个视频 https://www.bilibili.com/video/BV15Z4y197Ra
还算详细，应该只漏了ffmpeg的安装

**Comment by luobingit** [comment]
@lyqscmy 试了一下基本上没效果哦 能跑起来

**Comment by zengpeici** [comment]
> 只用于预测的容器镜像我已经构建好，内置预训练模型，本次测试跑过了。 docker run -p 8080:8080 -it jiada/mocking_bird

请问这个有后续的toolbox界面吗

**Comment by aiwibadi** [comment]
> 我总结一下吧，本人是小白，找的各处的教程拼起来的，可能会有错漏望指正。（安装CUDA的教程就不写了） 在CMD使用这个代码来检查你是否安装了CUDA `nvidia-smi` 注意：本流程中的任何路径都不能有空格！路径不能有空格！路径不能有空格！（重要的事情说三遍）
> 
> 下载python（下载python），win7后最多支持3.8.x 安装Anaconda3（[https://www.anaconda.com/products/individual#download-section），安好先手动添加环境变量（Windows](https://www.anaconda.com/products/individual#download-section%EF%BC%89%EF%BC%8C%E5%AE%89%E5%A5%BD%E5%90%8E%E6%89%8B%E5%8A%A8%E6%B7%BB%E5%8A%A0%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%EF%BC%88Windows)添加环境变量）电脑->用户选择路径->路径属性->高级设置->环境变量中设置。）
> 
> > D:\Anaconda 
> > D:\Anaconda\Scripts
> 
> 打开_promot_创建一个环境。 `conda create -n your_name jupyter notebook` 这句话的英文是为你的虚拟环境创建一个名字，并且这个虚拟环境安装jupyter notebook，额外的Anacon dacon库。 可以将你的名字改为你自己喜欢的名字，这个名字是你的虚拟环境的名字，自己随便取，比如jack。
> 
> > 请注意：这时候要打开 Anaconda 里面的 Anaconda Navigator (pythonAnaconda3) — 环境，鼠标找到自己刚创建的环境，在里面 python，点前面的小对那个，可以打开，移动到最找到的菜单中的标记为啥啥啥的，那里面能选python版本，创造的python环境用的不是我刚刚安装的python版本就很奇怪……记得改成自己能用的版本。
> 
> 安装好环境后，我们可以使用激活激活 jack 环境： `activate jack`
> 
> 下载作者的代码，解压后复制文件夹的路径。 然后这个时候去Anaconda菜单（杰克）<你创建下面的环境名字>，查看这里的属性-快捷方式-（在此处找到Jupyter的位置）粘贴刚才复制的路径，然后把路径里面的“\”这个符号换成“\”）。
> 
> 然后执行这个代码 `cd /d <E:\E\Jupyter>`里面那个的路径换成你刚才那个的
> 
> 下载安装PyTorch，选择为（1.9.1、windows、Conda、python、CUDA 10.2），执行下面这个代码。 `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`
> 
> 下载aidatatang_200zh，地址为 https://www.openslr.org/resources/62/aidatatang_200zh.tgz 反复压缩解压呢，直到没有压缩包为止，然后再把里面的压缩包只留下解压的文件18个G的文件，给你的硬盘腾点地方吧（笑） 注意：路径不能有空格！不能有空格！路径不能有空格！（重要的事情说三遍）
> 
> 下载作者的贴子模型 https://pan.baidu.com/s/1VHSKIbxXQejtxi2at9IrpA百度盘链接提取码：i183 把你下载的作者代码里面的synthesizer文件夹里面的saved_models（没有就创建一个）
> 
> 剩下的就是照着的步骤走走就可以运行叻...

可以加你个联系方式嘛，寻求一些安装指点！

**Comment by babysor** [comment]
> 求助，按照QuickStart安装顺利，运行.py文件报错如下 `Traceback (most recent call last): File "demo_toolbox.py", line 2, in <module> from toolbox import Toolbox File "C:\mockingBird\MockingBird-main\toolbox\__init__.py", line 1, in <module> from toolbox.ui import UI File "C:\mockingBird\MockingBird-main\toolbox\ui.py", line 7, in <module> from encoder.inference import plot_embedding_as_heatmap File "C:\mockingBird\MockingBird-main\encoder\inference.py", line 2, in <module> from encoder.model import SpeakerEncoder File "C:\mockingBird\MockingBird-main\encoder\model.py", line 5, in <module> from torch.nn.utils import clip_grad_norm_ ModuleNotFoundError: No module named 'torch'`

pytorch安装那一步没有成功

**Comment by zh-Spike** [comment]
> 只用于预测的容器镜像我已经构建好，内置预训练模型，本次测试跑过了。 docker run -p 8080:8080 -it jiada/mocking_bird

The docker image redislabs/redistimeseries latest throws an error on Jetson TX1:

WARNING: The requested image's platform (linux / amd64) does not match the detected host platform (linux / arm64 / v8) and no specific platform was requested
standard_init_linux.go: 228: exec user process caused: exec format error

This image in dockerhub are built for the x86_64 architecture. Would you like to build ARM version?
