### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading file data/39: invalid header or archive is corrupted

### ISSUE THREAD

**Issue by dazhao233** [babysor/MockingBird#131]
Traceback (most recent call last):
  File "E:\PyProjects\git_projects\MockingBird\toolbox\__init__.py", line 122, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "E:\PyProjects\git_projects\MockingBird\toolbox\__init__.py", line 236, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "E:\PyProjects\git_projects\MockingBird\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "E:\PyProjects\git_projects\MockingBird\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "E:\PyProjects\git_projects\MockingBird\synthesizer\models\tacotron.py", line 496, in load
    checkpoint = torch.load(str(path), map_location=device)
  File "D:\ProgramData\pyvenv\ml\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramData\pyvenv\ml\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "D:\ProgramData\pyvenv\ml\lib\site-packages\torch\serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "D:\ProgramData\pyvenv\ml\lib\site-packages\torch\serialization.py", line 845, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: PytorchStreamReader failed reading file data/39: invalid header or archive is corrupted

**Comment by dazhao233** [comment]
> saved_models文件夹里的zip文件需要移除

不行，我文件夹里面没有zip，你们查看一下百度云train3_200k.pt这个文件是不是损坏了，无论是运行demo_toolbox.py，还是web.py，都会报上面的错，我用torch.load()加载的时候也报上面的错误，说明这个文件可能是损坏了。
当然也可能是我下载过程损坏了，方便的话，可以提供一下train3_200k.pt文件的MD5值吗？谢谢。

**Comment by babysor** [comment]
是这个链接? 链接：https://pan.baidu.com/s/1VHSKIbxXQejtxi2at9IrpA 
提取码：i183

**Comment by babysor** [comment]
SHA256: 61450216577FD54B0658DADB4B562DCA5D62D6DBE54BA73B0A833FBA3D95A076

**Comment by 2635522924** [comment]
解决了吗
