### ISSUE TITLE
训练到7344/20414错误提示：_pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError

### ISSUE THREAD

**Issue by yinjia823** [babysor/MockingBird#132]
File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 319, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: Couldn't open shared file mapping: <0000029FFD7D77B2>, error code: <1455>
{| Epoch: 1/1 (7341/20414) | Loss: 0.7548 | 0.86 steps/s | Step: 7k | }Traceback (most recent call last):
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\site-packages\torch\multiprocessing\reductions.py", line 319, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: Couldn't open shared file mapping: <000001EBF5A60222>, error code: <1455>
{| Epoch: 1/1 (7342/20414) | Loss: 0.7547 | 0.86 steps/s | Step: 7k | }Traceback (most recent call last):
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError
{| Epoch: 1/1 (7343/20414) | Loss: 0.7564 | 0.87 steps/s | Step: 7k | }Traceback (most recent call last):
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "C:\Users\86158\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
**_pickle.PicklingError: Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError**
{| Epoch: 1/1 (7344/20414) | Loss: 0.7568 | 0.87 steps/s | Step: 7k | }Traceback (most recent call last):

大佬们 帮忙解决  /(ㄒoㄒ)/~~  训练了一天了 从早上到晚上

**Comment by babysor** [comment]
pytorch在并行处理时偶尔会出错，你有在同时运行什么程序吗？重新运行一下就好了应该

**Comment by yinjia823** [comment]
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|   10k Steps    |     8      |    0.0001     |        2         |
+----------------+------------+---------------+------------------+



重新运行 卡在这里了 …… 所以 再执行相同的命令了  这已经是第72个小时了 哈哈

**Comment by guilindd** [comment]
把batch_size改小就可以了
