### ISSUE TITLE
ImportError: Failed to import any qt binding

### ISSUE THREAD

**Issue by lNeverl** [babysor/MockingBird#158]
运行时报错 不知道为什么

**Comment by lNeverl** [comment]
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\pythonxiangmu\yuyinkelong\MockingBird\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\pythonxiangmu\yuyinkelong\MockingBird\toolbox\ui.py", line 2, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "D:\pythonxiangmu\anaconda\envs\yuyin\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "D:\pythonxiangmu\anaconda\envs\yuyin\lib\site-packages\matplotlib\backends\backend_qt5.py", line 13, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:\pythonxiangmu\anaconda\envs\yuyin\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "D:\pythonxiangmu\anaconda\envs\yuyin\lib\site-packages\matplotlib\backends\qt_compat.py", line 179, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
