### ISSUE TITLE
if np.isnan(grad_norm.cpu()): AttributeError: 'float' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by lcp580** [babysor/MockingBird#160]
运行环境：天池实验室notebook gpu
https://tianchi.aliyun.com/
https://dsw-dev.data.aliyun.com/
run:
!python synthesizer_train.py mandarin  /data/nas/workspace/jupyter/data/SV2TTS/synthesizer

==========
err:
Arguments:
    run_id:          mandarin
    syn_dir:         /data/nas/workspace/jupyter/data/SV2TTS/synthesizer
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    force_restart:   False
    hparams:         

Checkpoint path: synthesizer/saved_models/mandarin/mandarin.pt
Loading training data from: /data/nas/workspace/jupyter/data/SV2TTS/synthesizer/train.txt
Using model: Tacotron
[AMP WARNING][Frontend.cpp:121][1634655387:258952]Sleep 0.1s waiting for AMP Server socket: /tmp/harp/ccl_ipc_socket/system/server.socket
[AMP INFO][Frontend.cpp:152][1634655387:359287]pid=741, start to allocate gpu resource ...
Using device: cuda

Initialising Tacotron Model...

Trainable Parameters: 30.875M

Starting the training of Tacotron from scratch

Using inputs from:
	/data/nas/workspace/jupyter/data/SV2TTS/synthesizer/train.txt
	/data/nas/workspace/jupyter/data/SV2TTS/synthesizer/mels
	/data/nas/workspace/jupyter/data/SV2TTS/synthesizer/embeds
Found 9845 samples
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|   20k Steps    |     12     |     0.001     |        2         |
+----------------+------------+---------------+------------------+
 
Traceback (most recent call last):
  File "synthesizer_train.py", line 35, in <module>
    train(**vars(args))
  File "/data/nas/workspace/jupyter/MockingBird/synthesizer/train.py", line 200, in train
    if np.isnan(grad_norm.cpu()):
AttributeError: 'float' object has no attribute 'cpu'

**Comment by lcp580** [comment]
不过预训练python pre.py F:\data  -d BZNSYP -s，我是以前在其他windows server 2016训练成功后生成的SV2TTS目录下面的文件拷贝过去的。
