### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm.auto'

### ISSUE THREAD

**Issue by Tdzdele** [babysor/MockingBird#195]
PS C:\MockingBird> python demo_toolbox.py -d .\samples键入命令后报错
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\MockingBird\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\MockingBird\toolbox\ui.py", line 16, in <module>
    import umap
  File "C:\ProgramData\Anaconda3\lib\site-packages\umap\__init__.py", line 2, in <module>
    from .umap_ import UMAP
  File "C:\ProgramData\Anaconda3\lib\site-packages\umap\umap_.py", line 41, in <module>
    from umap.layouts import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\umap\layouts.py", line 5, in <module>
    from tqdm.auto import tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
这是什么问题啊

**Comment by babysor** [comment]
tqdm 版本好像有问题，你的环境有跟其他项目共用吗

**Comment by Tdzdele** [comment]
没有其他项目 之前我并没有过python的使用经验

**Comment by Tdzdele** [comment]
我把Anacodna卸载了 直接运行 现在报错发生了变化

**Comment by Tdzdele** [comment]
Traceback (most recent call last):
  File "C:\MockingBird\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\MockingBird\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\MockingBird\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by Tdzdele** [comment]
正在努力解决新的报错 遇到我无法解决的报错会再发出来

**Comment by Tdzdele** [comment]
再次安装必须库后已经可以正常运行了 应该是我在安装Anacodna和配置环境的时候哪里出了问题

**Comment by babysor** [comment]
> 已经可以正常运行了 应该是我在安装Anacodna和配置环境的时候哪里出了问题

环境 是最大的坎坷
