### ISSUE TITLE
使用训练库时出现问题

### ISSUE THREAD

**Issue by ygtcmc** [babysor/MockingBird#206]
ERROR in app: Exception on /api/synthesize [POST]
Traceback (most recent call last):
  File "d:\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Anaconda3\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "d:\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\声音模仿\web\__init__.py", line 111, in synthesize
    wav = rnn_vocoder.infer_waveform(spec)
  File "D:\声音模仿\vocoder\wavernn\inference.py", line 63, in infer_waveform
    wav = _model.generate(mel, batched, target, overlap, hp.mu_law, progress_callback)
  File "D:\声音模仿\vocoder\wavernn\models\fatchord_version.py", line 253, in generate
    output[-20 * self.hop_length:] *= fade_out
ValueError: operands could not be broadcast together with shapes (2400,) (4000,) (2400,)

**Comment by babysor** [comment]
输入得音频格式可能又点问题我，你有试过直接录音吗

**Comment by ygtcmc** [comment]
谢谢解答，有时间我会尝试并反馈
