### ISSUE TITLE
服务器训练模型在本地继续训练后，报错

### ISSUE THREAD

**Issue by ferretgeek** [babysor/MockingBird#210]
在服务器上训练的magicdata BS 84，训练到110K,。模型下载到本地，BS改为12，继续训练后，报错代码如下：
服务器训练采用的版本日期是10.24日。

F:\MockingBird\synthesizer\synthesizer_dataset.py:84: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  embeds = torch.tensor(embeds)
F:\MockingBird\synthesizer\synthesizer_dataset.py:84: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  embeds = torch.tensor(embeds)
C:\Users\ferret\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py:1795: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "F:\MockingBird\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "F:\MockingBird\synthesizer\train.py", line 208, in train
    optimizer.step()
  File "C:\Users\ferret\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ferret\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ferret\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 133, in step
    F.adam(params_with_grad,
  File "C:\Users\ferret\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\_functional.py", line 86, in adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3

**Comment by babysor** [comment]
本地的commit日期是？试过切换到10-24号的吗

**Comment by ferretgeek** [comment]
> 本地的commit日期是？试过切换到10-24号的吗

切换到24号的版本后正常了，想知道这个没有跟上最新版本，会影响训练效果吗？

**Comment by babysor** [comment]
影响比较小 当然建议如果效果一般的话尝试一下新版本

**Comment by ferretgeek** [comment]
> 影响比较小 当然建议如果效果一般的话尝试一下新版本

好的非常感谢。能回答这么多人的这么多问题，难为你了

**Comment by babysor** [comment]
> > 影响比较小 当然建议如果效果一般的话尝试一下新版本
> 
> 好的非常感谢。能回答这么多人的这么多问题，难为你了

需要像你一样的新兴力量加盟
