### ISSUE TITLE
训练时出错：RuntimeError: Error(s) in loading state_dict for Tacotron:

### ISSUE THREAD

**Issue by dsyrock** [babysor/MockingBird#211]
Arguments:
    run_id:          mandarin
    syn_dir:         k:/mockingbird/datame/SV2TTS/synthesizer
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    log_every:       200
    force_restart:   False
    hparams:

Checkpoint path: synthesizer\saved_models\mandarin\mandarin.pt
Loading training data from: k:\mockingbird\datame\SV2TTS\synthesizer\train.txt
Using model: Tacotron
Using device: cpu

Initialising Tacotron Model...

Trainable Parameters: 32.866M

Loading weights at synthesizer\saved_models\mandarin\mandarin.pt
Traceback (most recent call last):
  File "synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "K:\MockingBird\synthesizer\train.py", line 114, in train
    model.load(weights_fpath, optimizer)
  File "K:\MockingBird\synthesizer\models\tacotron.py", line 536, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "f:\anaconda3\envs\mockingbird\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([128, 1024]).
        size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 768]) from checkpoint, the shape in current model is torch.Size([384, 1280]).
        size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 640]) from checkpoint, the shape in current model is torch.Size([1024, 1152]).
        size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1, 2048]).

我已经把symbol里的那行字符改成旧版的那个了，还是报这个错。我这里用的是自己的数据，模仿aishell3的结构放了，已经做了 pre.py 的预处理，在开始训练这一步的时候就出了这个错

**Comment by dsyrock** [comment]
我换成 my_run8_25k.pt 这个模型来训练就可以了，readme里用的mandarin.pt就不行

**Comment by babysor** [comment]
> 我换成 my_run8_25k.pt 这个模型来训练就可以了，readme里用的mandarin.pt就不行
> 
> 另外他每一步都出现这个警告是什么意思呢？ {| Epoch: [25/10000](tel:25/10000) (1/1) | Loss: 4.027 | 0.15 steps/s | Step: 0k | } K:\MockingBird\synthesizer\synthesizer_dataset.py:84: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:201.) embeds = torch.tensor(embeds)

参考 #209
