### ISSUE TITLE
训练时出现这个错误

### ISSUE THREAD

**Issue by dsyrock** [babysor/MockingBird#219]
(mockingbird) K:\mb>python synthesizer_train.py 75k k:/mb/datame/SV2TTS/synthesizer -b 1000
Arguments:
    run_id:          75k
    syn_dir:         k:/mb/datame/SV2TTS/synthesizer
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    1000
    log_every:       200
    force_restart:   False
    hparams:

Checkpoint path: synthesizer\saved_models\75k\75k.pt
Loading training data from: k:\mb\datame\SV2TTS\synthesizer\train.txt
Using model: Tacotron
Using device: cpu

Initialising Tacotron Model...

Trainable Parameters: 32.869M

Loading weights at synthesizer\saved_models\75k\75k.pt
Tacotron weights loaded from step 93000
Using inputs from:
        k:\mb\datame\SV2TTS\synthesizer\train.txt
        k:\mb\datame\SV2TTS\synthesizer\mels
        k:\mb\datame\SV2TTS\synthesizer\embeds
Found 12 samples
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|   67k Steps    |     12     |     5e-06     |        2         |
+----------------+------------+---------------+------------------+

K:\mb\synthesizer\synthesizer_dataset.py:84: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  embeds = torch.tensor(embeds)
f:\anaconda3\envs\mockingbird\lib\site-packages\torch\nn\functional.py:1795: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "K:\mb\synthesizer\train.py", line 208, in train
    optimizer.step()
  File "f:\anaconda3\envs\mockingbird\lib\site-packages\torch\optim\optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "f:\anaconda3\envs\mockingbird\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "f:\anaconda3\envs\mockingbird\lib\site-packages\torch\optim\adam.py", line 133, in step
    F.adam(params_with_grad,
  File "f:\anaconda3\envs\mockingbird\lib\site-packages\torch\optim\_functional.py", line 86, in adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3

这个模型用的是主页提供的75k steps模型

**Comment by dsyrock** [comment]
似乎也是复用模型导致的，我从一个全新的模型开始训练的话就正常，但是我已经试过把hparams里的use_gst 和 use_ser_for_gst 都分别和一起生成False了，还是报错

**Comment by babysor** [comment]
拉最新的代码试试，应该有个bug - 最新commit描述了：pytorch对模块顺序有一定要求。

**Comment by dsyrock** [comment]
> 拉最新的代码试试，应该有个bug - 最新commit描述了：pytorch对模块顺序有一定要求。

用的就是最新的代码，结果是主页上挂的模型都无法复用，反而是我稍早一点下的版本里，75K那个模型可以接着训练

**Comment by babysor** [comment]
最新的应该可以啦 只有一个commit是不行的
