### ISSUE TITLE
快速上手最后一步执行时出现这个问题

### ISSUE THREAD

**Issue by moonofqing** [babysor/MockingBird#220]
E:\MockingBird-main>python demo_toolbox.py -d .\samples
Traceback (most recent call last):
  File "E:\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "E:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "E:\MockingBird-main\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by babysor** [comment]
是不是环境里有冲突 pip install的时候没安装好依赖

**Comment by as882301** [comment]
我也 遇到这个问题 不知道 什么 原因

**Comment by moonofqing** [comment]
已经解决，我发现是我用的python版本太新导致的


QJ ***@***.***> 于 2021年11月20日周六 下午8:24写道：

**Comment by JOJOda123** [comment]
有没有闪退呢，我之前启动GUI闪退了然后按照作者这个方法就可以了，链接：https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF
