### ISSUE TITLE
运行不了，找不到指定的模块

### ISSUE THREAD

**Issue by onesecplus6** [babysor/MockingBird#221]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\MockingBird-main\toolbox\ui.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 126, in <module>
    from . import cbook
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 34, in <module>
    import numpy as np
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: 找不到指定的模块。

**Comment by onesecplus6** [comment]
重装numpy后multiarray解决了，但还是不行
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\MockingBird-main\toolbox\ui.py", line 2, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 5, in <module>
    from .backend_qtagg import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum, _setDevicePixelRatio
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\qt_compat.py", line 128, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding

**Comment by babysor** [comment]
pip install过程有报错吗？可能依赖冲突了 试着用anaconda
