### ISSUE TITLE
有的时候点击合成，就出现报错

### ISSUE THREAD

**Issue by huankong233** [babysor/MockingBird#223]
报错内容：
Loaded encoder "pretrained.pt" trained to step 1594501
Synthesizer using device: cuda
Trainable Parameters: 32.869M
Traceback (most recent call last):
  File "C:\德丽莎\toolbox\__init__.py", line 123, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "C:\德丽莎\toolbox\__init__.py", line 238, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds, style_idx=int(self.ui.style_slider.value()), min_stop_token=min_token, steps=int(self.ui.length_slider.value())*200)
  File "C:\德丽莎\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "C:\德丽莎\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "C:\德丽莎\synthesizer\models\tacotron.py", line 547, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "D:\anaconda3\envs\Theresa\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).

**Comment by huankong233** [comment]
然后重新生成就又可以用了

**Comment by babysor** [comment]
有兼容错误，最新的代码分支吗？

**Comment by huankong233** [comment]
是的

**Comment by babysor** [comment]
用的哪个模型？

**Comment by huankong233** [comment]
https://www.bilibili.com/video/BV1DL4y1q7VL
这个视频里给的

**Comment by babysor** [comment]
> https://www.bilibili.com/video/BV1DL4y1q7VL 这个视频里给的

第三方模型嘛。。可能训练的时候用的旧代码，要切换一下
