### ISSUE TITLE
分享600kstep模型

### ISSUE THREAD

**Issue by Yuqi154** [babysor/MockingBird#239]
mockingbird
synthesizer-model
链接: https://pan.baidu.com/s/1t1UYixQFj40bd9rZ2blxng 
提取码: j23j 

使用aidatatang_200zh训练至600kstep
loss到0.3，在0.27-0.54波动

**Comment by lovethesummer** [comment]
好人一生平安

**Comment by johnwestin** [comment]
感谢分享！

**Comment by Yuqi154** [comment]
> mockingbird synthesizer-model 链接: https://pan.baidu.com/s/1t1UYixQFj40bd9rZ2blxng 提取码: j23j
> 
> 使用aidatatang_200zh训练至600kstep loss到0.3，在0.27-0.54波动
![attention_step_593000_sample_1](https://user-images.githubusercontent.com/92249309/143734633-12bb8d97-d7e6-4fa7-92d1-ad33ffd1d2e9.png)
![attention_step_600000_sample_1](https://user-images.githubusercontent.com/92249309/143734637-a4f51ec8-3868-4c63-b073-23ec9b042d72.png)


![step-596000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/92249309/143734648-f5e6bc31-199b-4ae1-9ae3-8ca23cf88e83.png)
![step-600000-mel-spectrogram_sample_1](https://user-images.githubusercontent.com/92249309/143734617-704e7224-a198-415c-8da8-7efe5dd73e16.png)

**Comment by linghushaoxia** [comment]
> j23j

RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
你使用的代码，是什么时候的，最新版本报错

**Comment by cocucola** [comment]
这个训练的相当不错

**Comment by GrilledPear** [comment]
@Yuqi154 尝试了 checkout v0.0.1 报错
checkout 之后按照 #37 修改依然报错
楼主还有另外修改吗？

**Comment by Fnlock1** [comment]
这个不错，很厉害

**Comment by Yuqi154** [comment]
使用的代码在0.0.1版本之前

**Comment by Yuqi154** [comment]
> > j23j
> 
> RuntimeError: Error(s) in loading state_dict for Tacotron: size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]). 你使用的代码，是什么时候的，最新版本报错

使用的代码在0.0.1之前

**Comment by delcompan** [comment]
分享的模型，要求0.0.1版的代码，ls老版本的在哪儿有

**Comment by luobingit** [comment]
@Yuqi154 你好  可以分享一下代码吗  我使用0.0.1版本的代码  用分享的模型还是报错哦

**Comment by HolaC** [comment]
@Yuqi154 同问，大大可以分享下这个模型用的是什么时候的代码版本吗？我也是用了tag0.0.1的版本，也是报错。报错如下

`Traceback (most recent call last):
  File "D:\Github\MockingBird-0.0.1\toolbox\__init__.py", line 123, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "D:\Github\MockingBird-0.0.1\toolbox\__init__.py", line 238, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds, style_idx=int(self.ui.style_slider.value()), min_stop_token=min_token)
  File "D:\Github\MockingBird-0.0.1\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "D:\Github\MockingBird-0.0.1\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "D:\Github\MockingBird-0.0.1\synthesizer\models\tacotron.py", line 523, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 1024]) from checkpoint, the shape in current model is torch.Size([128, 512]).
        size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 1280]) from checkpoint, the shape in current model is torch.Size([384, 768]).
        size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 1152]) from checkpoint, the shape in current model is torch.Size([1024, 640]).
        size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 2048]) from checkpoint, the shape in current model is torch.Size([1, 1536]).
Traceback (most recent call last):
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\backends\backend_qt.py", line 455, in _draw_idle
    self.draw()
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\figure.py", line 2789, in draw
    artists = self._get_draw_artists(renderer)
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\figure.py", line 238, in _get_draw_artists
    ax.apply_aspect()
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\axes\_base.py", line 1967, in apply_aspect
    self.set_xbound(x_trf.inverted().transform([x0, x1]))
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\axes\_base.py", line 3560, in set_xbound
    self.set_xlim(sorted((lower, upper),
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\axes\_base.py", line 3684, in set_xlim
    left = self._validate_converted_limits(left, self.convert_xunits)
  File "D:\PCInstall\Code\Anaconda3\envs\bird\lib\site-packages\matplotlib\axes\_base.py", line 3601, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf`

**Comment by Yuqi154** [comment]
版本是11.6号的zip，
下载链接: https://pan.baidu.com/s/1kR1Qqd7xA4e1c66a2E-Fug 提取码: 24bf

**Comment by xxxolllllllll** [comment]
这个模型我用带.mp4后缀的文件作为输入，输出的声音就糊了，我把后缀改了之后依旧如此，其他.wav好像没有问题

**Comment by hclakk** [comment]
可以請求一個模型放在google雲的連結嗎? 謝謝

**Comment by hclakk** [comment]
> > 可以請求一個模型放在google雲的連結嗎? 謝謝
> 
> 可能不行，OneDrive可以吗？

沒有問題 麻煩您了 再次感謝

**Comment by Yuqi154** [comment]
> > > 可以請求一個模型放在google雲的連結嗎? 謝謝
> > 
> > 
> > 可能不行，OneDrive可以吗？
> 
> 沒有問題 麻煩您了 再次感謝


感谢大陆比乌龟还慢的网速，现在有了
https://1drv.ms/u/s!ArkeI_kGgBy2gtAHYi5T5xvfMhSpYg?e=UgGXN5

**Comment by Summerxu86** [comment]
> mockingbird synthesizer-model 链接: https://pan.baidu.com/s/1t1UYixQFj40bd9rZ2blxng 提取码: j23j
> 
> 使用aidatatang_200zh训练至600kstep loss到0.3，在0.27-0.54波动

请问batchsize设的多少呀？我用aidatatang_200zh数据集训练，到200kstep loss一直在0.5左右下不去了，这样正常吗？

**Comment by 5l1v3r1** [comment]
Can anyone upload it to another cloud rather than baidu please? You know it is a hassle to download those files abroad.

**Comment by jx06T** [comment]
發現OneDrive的檔案似乎過期了 有沒有人能幫忙分享一下到不是百度的盤

**Comment by weixiu00** [comment]
这个有测试过吗，我这边试了下，对比其他模型，这个效果特别差，克隆的声音都说不出话

**Comment by Yuqi154** [comment]
> 这个有测试过吗，我这边试了下，对比其他模型，这个效果特别差，克隆的声音都说不出话

这个.....好久之前的了，你还是选择更好的模型吧。也可能是代码版本不一样。
