### ISSUE TITLE
只有CPU没有GPU的机器，始终无法生成成功，只有2秒的电流音

### ISSUE THREAD

**Issue by work4seo** [babysor/MockingBird#242]
**python版本：**
`C:\Program Files (x86)\MockingBird-main>python -V
Python 3.9.9`

**各类库文件版本**
`C:\Program Files (x86)\MockingBird-main>pip list
Package                 Version
----------------------- ------------
absl-py                 1.0.0
aniso8601               9.0.1
appdirs                 1.4.4
attrs                   21.2.0
audioread               2.1.9
cachetools              4.2.4
certifi                 2021.10.8
cffi                    1.15.0
charset-normalizer      2.0.8
click                   8.0.3
colorama                0.4.4
cycler                  0.11.0
decorator               5.1.0
dill                    0.3.4
Flask                   2.0.2
Flask-Cors              3.0.10
flask-restx             0.5.1
Flask-WTF               1.0.0
fonttools               4.28.2
gevent                  21.8.0
google-auth             2.3.3
google-auth-oauthlib    0.4.6
greenlet                1.1.2
grpcio                  1.42.0
idna                    3.3
importlib-metadata      4.8.2
inflect                 5.3.0
itsdangerous            2.0.1
Jinja2                  3.0.3
joblib                  1.1.0
jsonpatch               1.32
jsonpointer             2.2
jsonschema              4.2.1
kiwisolver              1.3.2
librosa                 0.8.1
llvmlite                0.37.0
Markdown                3.3.6
MarkupSafe              2.0.1
matplotlib              3.5.0
multiprocess            0.70.12.2
numba                   0.54.1
numpy                   1.19.3
oauthlib                3.1.1
packaging               21.3
Pillow                  8.4.0
pip                     21.3.1
pooch                   1.5.2
protobuf                3.19.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pynndescent             0.5.5
pyparsing               3.0.6
pypinyin                0.44.0
PyQt5                   5.15.6
PyQt5-Qt5               5.15.2
PyQt5-sip               12.9.0
pyrsistent              0.18.0
python-dateutil         2.8.2
pytz                    2021.3
pyzmq                   22.3.0
requests                2.26.0
requests-oauthlib       1.3.0
resampy                 0.2.2
rsa                     4.8
scikit-learn            1.0.1
scipy                   1.7.3
setuptools              59.4.0
setuptools-scm          6.3.2
six                     1.16.0
sounddevice             0.4.3
SoundFile               0.10.3.post1
tensorboard             2.7.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
threadpoolctl           3.0.0
tomli                   1.2.2
torch                   1.10.0
torchaudio              0.10.0
torchfile               0.1.0
torchvision             0.11.1
tornado                 6.1
tqdm                    4.62.3
typing_extensions       4.0.0
umap-learn              0.5.2
Unidecode               1.3.2
urllib3                 1.26.7
visdom                  0.1.8.9
webrtcvad-wheels        2.0.10.post2
websocket-client        1.2.1
Werkzeug                2.0.2
wheel                   0.37.0
WTForms                 3.0.0
zipp                    3.6.0
zope.event              4.5.0
zope.interface          5.4.0`

**报错信息（）：**
`C:\Program Files (x86)\MockingBird-main>python web.py
Loaded synthesizer models: 2
Loaded encoder "pretrained.pt" trained to step 1594501
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Building hifigan
Loading 'vocoder\saved_models\pretrained\g_hifigan.pt'
Complete.
Removing weight norm...
Web server:http://localhost:8080
127.0.0.1 - - [2021-11-29 20:10:48] "GET / HTTP/1.1" 200 16488 0.019554
127.0.0.1 - - [2021-11-29 20:10:48] "GET /static/js/wav.js HTTP/1.1" 304 137 0.178753
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/frequency.histogram.view.js HTTP/1.1" 304 158 0.003109
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/mp3.js HTTP/1.1" 304 137 0.003626
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/jquery.js HTTP/1.1" 304 140 0.004169
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/mp3-engine.js HTTP/1.1" 304 144 0.003167
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/lib.fft.js HTTP/1.1" 304 141 0.002072
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/recorder-core.js HTTP/1.1" 304 147 0.003670
127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/img/bird.png HTTP/1.1" 304 139 0.004651
127.0.0.1 - - [2021-11-29 20:10:49] "GET /api/synthesizers/ HTTP/1.1" 200 264 0.001592
Synthesizer using device: cpu
using synthesizer model: synthesizer\saved_models\ceshi.pt
Trainable Parameters: 32.869M
[2021-11-29 20:11:04,797] ERROR in app: Exception on /api/synthesize [POST]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Program Files (x86)\MockingBird-main\web\__init__.py", line 108, in synthesize
    specs = current_synt.synthesize_spectrograms(texts, embeds)
  File "C:\Program Files (x86)\MockingBird-main\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "C:\Program Files (x86)\MockingBird-main\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "C:\Program Files (x86)\MockingBird-main\synthesizer\models\tacotron.py", line 544, in load
    checkpoint = torch.load(str(path))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
127.0.0.1 - - [2021-11-29 20:11:04] "POST /api/synthesize HTTP/1.1" 500 426 2.548924
`

**Comment by work4seo** [comment]
不管是web版本，还是GUI版本，都无法生成正确的录音，都只有2秒的电流音。
已经按照https://github.com/babysor/MockingBird/issues/37这个里面的提示修改了字符集。

测试环境：腾讯云2C+4G的标准版云服务器，Windows 2019版本

**Comment by work4seo** [comment]
> **python版本：** `C:\Program Files (x86)\MockingBird-main>python -V Python 3.9.9`
> 
> **各类库文件版本** `C:\Program Files (x86)\MockingBird-main>pip list Package Version
> 
> absl-py 1.0.0 aniso8601 9.0.1 appdirs 1.4.4 attrs 21.2.0 audioread 2.1.9 cachetools 4.2.4 certifi 2021.10.8 cffi 1.15.0 charset-normalizer 2.0.8 click 8.0.3 colorama 0.4.4 cycler 0.11.0 decorator 5.1.0 dill 0.3.4 Flask 2.0.2 Flask-Cors 3.0.10 flask-restx 0.5.1 Flask-WTF 1.0.0 fonttools 4.28.2 gevent 21.8.0 google-auth 2.3.3 google-auth-oauthlib 0.4.6 greenlet 1.1.2 grpcio 1.42.0 idna 3.3 importlib-metadata 4.8.2 inflect 5.3.0 itsdangerous 2.0.1 Jinja2 3.0.3 joblib 1.1.0 jsonpatch 1.32 jsonpointer 2.2 jsonschema 4.2.1 kiwisolver 1.3.2 librosa 0.8.1 llvmlite 0.37.0 Markdown 3.3.6 MarkupSafe 2.0.1 matplotlib 3.5.0 multiprocess 0.70.12.2 numba 0.54.1 numpy 1.19.3 oauthlib 3.1.1 packaging 21.3 Pillow 8.4.0 pip 21.3.1 pooch 1.5.2 protobuf 3.19.1 pyasn1 0.4.8 pyasn1-modules 0.2.8 pycparser 2.21 pynndescent 0.5.5 pyparsing 3.0.6 pypinyin 0.44.0 PyQt5 5.15.6 PyQt5-Qt5 5.15.2 PyQt5-sip 12.9.0 pyrsistent 0.18.0 python-dateutil 2.8.2 pytz 2021.3 pyzmq 22.3.0 requests 2.26.0 requests-oauthlib 1.3.0 resampy 0.2.2 rsa 4.8 scikit-learn 1.0.1 scipy 1.7.3 setuptools 59.4.0 setuptools-scm 6.3.2 six 1.16.0 sounddevice 0.4.3 SoundFile 0.10.3.post1 tensorboard 2.7.0 tensorboard-data-server 0.6.1 tensorboard-plugin-wit 1.8.0 threadpoolctl 3.0.0 tomli 1.2.2 torch 1.10.0 torchaudio 0.10.0 torchfile 0.1.0 torchvision 0.11.1 tornado 6.1 tqdm 4.62.3 typing_extensions 4.0.0 umap-learn 0.5.2 Unidecode 1.3.2 urllib3 1.26.7 visdom 0.1.8.9 webrtcvad-wheels 2.0.10.post2 websocket-client 1.2.1 Werkzeug 2.0.2 wheel 0.37.0 WTForms 3.0.0 zipp 3.6.0 zope.event 4.5.0 zope.interface 5.4.0`
> 
> **报错信息（）：** `C:\Program Files (x86)\MockingBird-main>python web.py Loaded synthesizer models: 2 Loaded encoder "pretrained.pt" trained to step 1594501 Building Wave-RNN Trainable Parameters: 4.481M Loading model weights at vocoder\saved_models\pretrained\pretrained.pt Building hifigan Loading 'vocoder\saved_models\pretrained\g_hifigan.pt' Complete. Removing weight norm... Web server:http://localhost:8080 127.0.0.1 - - [2021-11-29 20:10:48] "GET / HTTP/1.1" 200 16488 0.019554 127.0.0.1 - - [2021-11-29 20:10:48] "GET /static/js/wav.js HTTP/1.1" 304 137 0.178753 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/frequency.histogram.view.js HTTP/1.1" 304 158 0.003109 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/mp3.js HTTP/1.1" 304 137 0.003626 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/jquery.js HTTP/1.1" 304 140 0.004169 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/mp3-engine.js HTTP/1.1" 304 144 0.003167 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/lib.fft.js HTTP/1.1" 304 141 0.002072 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/js/recorder-core.js HTTP/1.1" 304 147 0.003670 127.0.0.1 - - [2021-11-29 20:10:49] "GET /static/img/bird.png HTTP/1.1" 304 139 0.004651 127.0.0.1 - - [2021-11-29 20:10:49] "GET /api/synthesizers/ HTTP/1.1" 200 264 0.001592 Synthesizer using device: cpu using synthesizer model: synthesizer\saved_models\ceshi.pt Trainable Parameters: 32.869M [2021-11-29 20:11:04,797] ERROR in app: Exception on /api/synthesize [POST] Traceback (most recent call last): File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_restx\api.py", line 672, in error_router return original_handler(e) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "C:\Program Files (x86)\MockingBird-main\web\__init__.py", line 108, in synthesize specs = current_synt.synthesize_spectrograms(texts, embeds) File "C:\Program Files (x86)\MockingBird-main\synthesizer\inference.py", line 87, in synthesize_spectrograms self.load() File "C:\Program Files (x86)\MockingBird-main\synthesizer\inference.py", line 65, in load self._model.load(self.model_fpath) File "C:\Program Files (x86)\MockingBird-main\synthesizer\models\tacotron.py", line 544, in load checkpoint = torch.load(str(path)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 607, in load return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 882, in _load result = unpickler.load() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 857, in persistent_load load_tensor(data_type, size, key, _maybe_decode_ascii(location)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 846, in load_tensor loaded_storages[key] = restore_location(storage, location) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 175, in default_restore_location result = fn(storage, location) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 151, in _cuda_deserialize device = validate_cuda_device(location) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 135, in validate_cuda_device raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU. 127.0.0.1 - - [2021-11-29 20:11:04] "POST /api/synthesize HTTP/1.1" 500 426 2.548924 `


`C:\Program Files (x86)\MockingBird-main>python demo_toolbox.py
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder\saved_models
    syn_models_dir:   synthesizer\saved_models
    voc_models_dir:   vocoder\saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
        aidatatang_200zh/corpus/dev
        aidatatang_200zh/corpus/test
        aishell3/test/wav
        magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Loaded encoder "pretrained.pt" trained to step 1594501
Synthesizer using device: cpu
Trainable Parameters: 32.869M
Traceback (most recent call last):
  File "C:\Program Files (x86)\MockingBird-main\toolbox\__init__.py", line 123, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "C:\Program Files (x86)\MockingBird-main\toolbox\__init__.py", line 238, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds, style_idx=int(self.ui.style_slider.value()), min_stop_token=min_token, steps=int(self.ui.length_slider.value())*200)
  File "C:\Program Files (x86)\MockingBird-main\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "C:\Program Files (x86)\MockingBird-main\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "C:\Program Files (x86)\MockingBird-main\synthesizer\models\tacotron.py", line 544, in load
    checkpoint = torch.load(str(path))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
QWindowsWindow::setGeometry: Unable to set geometry 1876x837+0+23 (frame: 1892x876-8-8) on QWidgetWindow/"UIClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1440x837+0+23 (frame: 1456x876-8-8) margins: 8, 31, 8, 8 minimum size: 1876x428 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1892,467 maxtrack=0,0)
Read ['欢迎使用工具箱', '现已支持中文输入']
Synthesizing ['huan1 ying2 shi3 yong4 gong1 ju4 xiang1', 'xian4 yi3 zhi1 chi2 zhong1 wen2 shu1 ru4']

| Generating 1/1


Done.

Building hifigan
Loading 'vocoder\saved_models\pretrained\g_hifigan.pt'
Complete.
Removing weight norm...
`


不管是web版本，还是GUI版本，都无法生成正确的录音，都只有2秒的电流音。
已经按照https://github.com/babysor/MockingBird/issues/37    这个里面的提示修改了字符集。

测试环境：腾讯云2C+4G的标准版云服务器，Windows 2019版本。

也在群里面按照其他同学的提示，修改了synthesizer/train.py 文件中的loaded_shape = torch.load(str(weights_fpath), map_location=device)，强行定义为loaded_shape = torch.load(str(weights_fpath), map_location="cpu")，但错误依旧。

![1638188956(1)](https://user-images.githubusercontent.com/10250695/143868384-6029d3a4-7936-41c7-a6a0-11c08c6a003a.png)

**Comment by babysor** [comment]
尝试拉最新main，最新commit有做了一定的device信息传递

**Comment by work4seo** [comment]
> 尝试拉最新main，最新commit有做了一定的device信息传递

感谢回复，刚刚拉了最新版的，问题依旧

**Comment by babysor** [comment]
看提示，需要你改成 `map_location=torch.device('cpu')` 而不是 `map_location='cpu'`

**Comment by YahuiWong** [comment]
使用 python demo_toolbox.py --cpu  之后依然是只有两声电流声

**Comment by babysor** [comment]
@work4seo 尝试过吗，改成 map_location=torch.device('cpu')

**Comment by whitespeed** [comment]
我的也是

**Comment by DocMine** [comment]
我的也是cpu机器，强制将train.py改到loaded_shape = torch.load(str(weights_fpath), map_location=torch.device("cpu"))后问题依旧；
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([128, 1024]).
        size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 768]) from checkpoint, the shape in current model is torch.Size([384, 1280]).
        size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 640]) from checkpoint, the shape in current model is torch.Size([1024, 1152]).
        size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1, 2048]).

**Comment by babysor** [comment]
> 我的也是cpu机器，强制将train.py改到loaded_shape = torch.load(str(weights_fpath), map_location=torch.device("cpu"))后问题依旧； RuntimeError: Error(s) in loading state_dict for Tacotron: size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([128, 1024]). size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 768]) from checkpoint, the shape in current model is torch.Size([384, 1280]). size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 640]) from checkpoint, the shape in current model is torch.Size([1024, 1152]). size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1, 2048]).

这个跟cpu没关系，看下issue相关解决方法
