### ISSUE TITLE
打扰大佬，请问报错 No such file or directory该如何解决呢，在J:\ImitateSound\MockingBird-main\vocoder\saved_models\pretrained下可以看到pretrained.pt 

### ISSUE THREAD

**Issue by NeedStudy** [babysor/MockingBird#247]
Traceback (most recent call last):
  File "J:\ImitateSound\MockingBird-main\pre.py", line 76, in <module>
    create_embeddings(synthesizer_root=args.out_dir, n_processes=n_processes_embed, encoder_model_fpath=encoder_model_fpath)
  File "J:\ImitateSound\MockingBird-main\synthesizer\preprocess.py", line 120, in create_embeddings
    list(tqdm(job, "Embedding", len(fpaths), unit="utterances"))
  File "C:\Users\62433\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\std.py", line 1180, in __iter__
    for obj in iterable:
  File "C:\Users\62433\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'encoder\\saved_models\\pretrained.pt'

C:\Users\62433>python J:\ImitateSound\MockingBird-main\pre.py J:\xunlianji\ -d aishell3 -n 15

**Comment by NeedStudy** [comment]
![image](https://user-images.githubusercontent.com/35551637/144763744-99541e39-6e85-41ed-97e4-0f67d0027734.png)
可以看到是有的，这个该如何解决呢，大佬

**Comment by NeedStudy** [comment]
全部内容报错如下，
![image](https://user-images.githubusercontent.com/35551637/144764106-5a860d2d-bf5d-4052-8eba-d713ccadb5f2.png)
