### ISSUE TITLE
最后一步报错ModuleNotFoundError: No module named 'umap'

### ISSUE THREAD

**Issue by wanxuntong** [babysor/MockingBird#264]
第一次让我选择打开方式，我选的python，之后就报错了，用pip更新显示没包，安装显示已有，但运行python demo_toolbox.py还是报错

**Comment by wanxuntong** [comment]
E:\Internet\MockingBird-main\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "E:\Internet\MockingBird-main\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "E:\Internet\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "E:\Internet\MockingBird-main\MockingBird-main\toolbox\ui.py", line 16, in <module>
    import umap
ModuleNotFoundError: No module named 'umap'

**Comment by wanxuntong** [comment]
问题已解决，重启然后pip install umap
