### ISSUE TITLE
"AssertionError" when starting web.py | 运行web.py时出现"AssertionError"错误

### ISSUE THREAD

**Issue by GreenApple-King** [babysor/MockingBird#266]
When I started "web.py", I met the error message ended of "AssertionError".:
我用python运行"web.py"时，遇到了以下问题，最后一行是“AssertionError”：

(mockingbird) C:\Users\yisheng_zhou\Downloads\MockingBird> python web.py
Loaded synthesizer models: 2
Loaded encoder "pretrained.pt" trained to step 1564501
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Building hifigan
Traceback (most recent call last):
  File "C:\Users\yisheng_zhou\Downloads\MockingBird\web.py", line 6, in <module>
    app = webApp()
  File "C:\Users\yisheng_zhou\Downloads\MockingBird\web\__init__.py", line 35, in webApp
    gan_vocoder.load_model(Path("vocoder/saved_models/pretrained/g_hifigan.pt"))
  File "C:\Users\yisheng_zhou\Downloads\MockingBird\vocoder\hifigan\inference.py", line 44, in load_model
    state_dict_g = load_checkpoint(
  File "C:\Users\yisheng_zhou\Downloads\MockingBird\vocoder\hifigan\inference.py", line 18, in load_checkpoint
    assert os.path.isfile(filepath)
AssertionError

Was someone same to me? How to solve?
各位大神有遇到和我一样问题的吗？怎么解决的？

**Comment by babysor** [comment]
file of vocoder/saved_models/pretrained/g_hifigan.pt is missing?
