### ISSUE TITLE
进行音频和梅尔频谱图预处理报错怎么回事： python encoder_preprocess.py <datasets_root>

### ISSUE THREAD

**Issue by LiangChenStart** [babysor/MockingBird#271]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "E:\PythonProject\MockingBird\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

**Comment by Feyman91** [comment]
同样的问题，请问楼主解决了吗

**Comment by babysor** [comment]
数据集文件没有正常解压

**Comment by MrWeijing** [comment]
出现这个错误可能的原因：
1、<你数据集的根目录>\corpus\train   这个路径下面的音频文件是一个压缩文件，此时需要把该文件在当前目录解压缩；
2、你可能直接把所有用于训练的n个音频文件直接放在 “ <你数据集的根目录>\corpus\train ” 这个路径下面，而没有把这些音频文件打包成一个文件夹的形式，此时应该新建一个文件夹（文件名为英文，具体命名自拟），然后将所有的音频文件放入其中。

**Comment by flysmart** [comment]
我今天也碰到这个问题已成功解决    
解压后发现G00XX下面还有个子文件夹G00XX  你需要把第二级的G00XX文件夹直接放在\train下 问题解决！

**Comment by fanjiafu** [comment]
解压后可以把原压缩包删除吧

**Comment by HaSaKiYasuooo** [comment]
> 出现这个错误可能的原因： 1、<你数据集的根目录>\corpus\train 这个路径下面的音频文件是一个压缩文件，此时需要把该文件在当前目录解压缩； 2、你可能直接把所有用于训练的n个音频文件直接放在 “ <你数据集的根目录>\corpus\train ” 这个路径下面，而没有把这些音频文件打包成一个文件夹的形式，此时应该新建一个文件夹（文件名为英文，具体命名自拟），然后将所有的音频文件放入其中。

我按照格式进行放置，没有成功
