### ISSUE TITLE
报错，不报错的时候有杂音

### ISSUE THREAD

**Issue by 1Wizzy** [babysor/MockingBird#278]
报错信息：
Traceback (most recent call last):
  File "E:\AI\Project\MockingBird\MockingBird-main\toolbox\__init__.py", line 123, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "E:\AI\Project\MockingBird\MockingBird-main\toolbox\__init__.py", line 272, in vocode
    wav = vocoder.infer_waveform(spec, progress_callback=vocoder_progress)
  File "E:\AI\Project\MockingBird\MockingBird-main\vocoder\wavernn\inference.py", line 63, in infer_waveform
    wav = _model.generate(mel, batched, target, overlap, hp.mu_law, progress_callback)
  File "E:\AI\Project\MockingBird\MockingBird-main\vocoder\wavernn\models\fatchord_version.py", line 253, in generate
    output[-20 * self.hop_length:] *= fade_out
ValueError: operands could not be broadcast together with shapes (2400,) (4000,) (2400,)
杂音问题：
全是杂音，没有一点人声，支持CUDA，数据集和自己录制声音都不能正确正确生成出一点声音，
encoder:pretrained.pt
synthesizer:ceshi.pt, mandarin_200k.pt
vocoder:g_hifigan.pt,pretrained.pt,wavernn_pretrained.pt
以上任何搭配都无法生成正常的声音
按照issue #37 修改前后也存在上述所有问题。

**Comment by 1Wizzy** [comment]
![image](https://user-images.githubusercontent.com/54066145/146628959-590b6475-13fc-4078-8deb-fe793a305716.png)
报错问题截图如上

**Comment by whitespeed** [comment]
同上问题

**Comment by 1Wizzy** [comment]
切换tag就行
