### ISSUE TITLE
运行pre.py时报错

### ISSUE THREAD

**Issue by hutianyu2006** [babysor/MockingBird#290]
完整输出：
PS D:\MockingBird> python pre.py D:\
Using data from:
    D:\aidatatang_200zh\corpus\train
aidatatang_200zh:   6%|███▎                                                   | 50/840 [23:39<6:13:51, 28.39s/speakers]
Traceback (most recent call last):
  File "D:\MockingBird\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "D:\MockingBird\synthesizer\preprocess.py", line 74, in preprocess_dataset
    for speaker_metadata in tqdm(job, dataset, len(speaker_dirs), unit="speakers"):
  File "E:\python\lib\site-packages\tqdm\std.py", line 1180, in __iter__
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "E:\python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "E:\python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\python\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "E:\python\lib\multiprocessing\queues.py", line 368, in get
    return _ForkingPickler.loads(res)
MemoryError
    for obj in iterable:
  File "E:\python\lib\multiprocessing\pool.py", line 870, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x000002734060DD30>'. Reason: 'PicklingError("Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError")'
Traceback (most recent call last):
  File "E:\python\lib\multiprocessing\util.py", line 300, in _run_finalizers
    finalizer()
  File "E:\python\lib\multiprocessing\util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "E:\python\lib\multiprocessing\pool.py", line 692, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "E:\python\lib\multiprocessing\pool.py", line 674, in _help_stuff_finish
    inqueue._reader.recv()
  File "E:\python\lib\multiprocessing\connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
MemoryError

内存16G，硬盘剩余空间200G，CPU i7-6700HQ，显卡 NVIDIA Geforce GTX 960M，仓库昨天刚clone的，PyTorch是最新版

**Comment by wrk226** [comment]
1.试试降低n_processer
2.试试把MockingBird/synthesizer/preprocess.py 的73~76行改成
```
    pool = Pool(n_processes)
    job = pool.imap(func, speaker_dirs)
    for speaker_metadata in tqdm(job, dataset, len(speaker_dirs), unit="speakers"):
        for metadatum in speaker_metadata:
            metadata_file.write("|".join(str(x) for x in metadatum) + "\n")
    pool.close()
```

**Comment by hutianyu2006** [comment]
> 

解决啦，谢谢
