### ISSUE TITLE
我这段有问题， 有点搞不懂

### ISSUE THREAD

**Issue by jacktang0705** [babysor/MockingBird#303]
Arguments:
datasets_root: /Users/xxx/Desktop/hoop/Realtime-Voice-Clone-Chinese/aidatatang_200zh
out_dir: /Users/xxx/Desktop/hoop/Realtime-Voice-Clone-Chinese/aidatatang_200zh/SV2TTS/synthesizer
n_processes: None
skip_existing: False
hparams:
no_alignments: False
dataset: aidatatang_200zh

Using data from:
/Users/xxx/Desktop/hoop/Realtime-Voice-Clone-Chinese/aidatatang_200zh/aidatatang_200zh/corpus/train
Traceback (most recent call last):
File "/Users/xxx/Desktop/hoop/Realtime-Voice-Clone-Chinese/synthesizer_preprocess_audio.py", line 63, in <module>
preprocess_dataset(**vars(args))
File "/Users/xxx/Desktop/hoop/Realtime-Voice-Clone-Chinese/synthesizer/preprocess.py", line 32, in preprocess_dataset
assert all(input_dir.exists() for input_dir in input_dirs)
AssertionError

**Comment by babysor** [comment]
路径错误

**Comment by ximing99** [comment]
问题解决了吗，我又遇到了
