### ISSUE TITLE
AttributeError: module 'setuptools._distutils' has no attribute 'version'

### ISSUE THREAD

**Issue by Dustwinddd** [babysor/MockingBird#304]
F:\VideoCentTools\MockingBird-main>python synthesizer_train.py offhen F:\VideoCentTools/SV2TTS/synthesizer
Traceback (most recent call last):
  File "F:\VideoCentTools\MockingBird-main\synthesizer_train.py", line 2, in <module>
    from synthesizer.train import train
  File "F:\VideoCentTools\MockingBird-main\synthesizer\train.py", line 5, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'setuptools._distutils' has no attribute 'version'

**Comment by babysor** [comment]
tensorboard 在你电脑有版本问题，请用干净的虚拟python环境

**Comment by Dustwinddd** [comment]
那么我需要退回到哪一步呢 我发现即使我pip uninstall tensorboard之后run以及再pip install -r requirements.txt之后run都还是出现这个结果

**Comment by babysor** [comment]
> 那么我需要退回到哪一步呢 我发现即使我pip uninstall tensorboard之后run以及再pip install -r requirements.txt之后run都还是出现这个结果

建议用anaconda工具创建虚拟环境

**Comment by Dustwinddd** [comment]
我只能说感谢您提供的意见。
由于我不甚了解python 我只能勉强理解步骤的逻辑
我搜索了anaconda工具并且查询了教程
安装了pycharm和anaconda
我发现它们在安装的时候跳过了很多分支的安装
所以我又回头 尝试run在我本体上的

**Comment by Dustwinddd** [comment]
A:	安装anaconda和pycharm

Q:	发现缺少torch、torchvision、torchaudio

A:	安装torch

Q:	发现缺少tensorboard

A:	pip install tensorboard 

Q:	发现缺少librosa

A:	pip install librosa

**Comment by Dustwinddd** [comment]
Q:	F:\VideoCentTools\MockingBird-main>python synthesizer_train.py offhen F:\VideoCentTools/SV2TTS/synthesizer
Traceback (most recent call last):
  File "F:\VideoCentTools\MockingBird-main\synthesizer_train.py", line 2, in <module>
    from synthesizer.train import train
  File "F:\VideoCentTools\MockingBird-main\synthesizer\train.py", line 6, in <module>
    from synthesizer import audio
  File "F:\VideoCentTools\MockingBird-main\synthesizer\audio.py", line 1, in <module>
    import librosa
  File "L:\Anaconda3\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "L:\Anaconda3\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "L:\Anaconda3\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "L:\Anaconda3\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "L:\Anaconda3\lib\site-packages\librosa\util\__init__.py", line 87, in <module>
    from ._nnls import *  # pylint: disable=wildcard-import
  File "L:\Anaconda3\lib\site-packages\librosa\util\_nnls.py", line 13, in <module>
    import scipy.optimize
  File "L:\Anaconda3\lib\site-packages\scipy\optimize\__init__.py", line 400, in <module>
    from .optimize import *
  File "L:\Anaconda3\lib\site-packages\scipy\optimize\optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "L:\Anaconda3\lib\site-packages\scipy\optimize\_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "L:\Anaconda3\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "L:\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "L:\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "L:\Anaconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed while importing _arpack: 找不到指定的程序。

**Comment by Dustwinddd** [comment]
A:	pip uninstall scipy & pip install scipy

Q:	缺少inflect

A:	pip install inflect

done.

**Comment by Dustwinddd** [comment]
结果发现能run了 喜从天降

**Comment by babysor** [comment]
哈哈 是不是缺少重启
