### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by 123LIAO** [babysor/MockingBird#312]
使用web.py时报错
Synthesizer using device: cpu
using synthesizer model: synthesizer\saved_models\mandarin.pt
Trainable Parameters: 32.869M
[2022-01-03 17:26:11,443] ERROR in app: Exception on /api/synthesize [POST]
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\MockingBird-main\MockingBird-main\web\__init__.py", line 108, in synthesize
    specs = current_synt.synthesize_spectrograms(texts, embeds)
  File "D:\MockingBird-main\MockingBird-main\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "D:\MockingBird-main\MockingBird-main\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath, self.device)
  File "D:\MockingBird-main\MockingBird-main\synthesizer\models\tacotron.py", line 547, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "C:\Python38\lib\site-packages\torch\nn\modules\module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder_proj.weight: copying a param with shape torch.Size([128, 512]) from checkpoint, the shape in current model is torch.Size([128, 1024]).
        size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for decoder.attn_rnn.weight_ih: copying a param with shape torch.Size([384, 768]) from checkpoint, the shape in current model is torch.Size([384, 1280]).
        size mismatch for decoder.rnn_input.weight: copying a param with shape torch.Size([1024, 640]) from checkpoint, the shape in current model is torch.Size([1024, 1152]).
        size mismatch for decoder.stop_proj.weight: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1, 2048]).
127.0.0.1 - - [2022-01-03 17:26:11] "POST /api/synthesize HTTP/1.1" 500 426 1.459210

**Comment by Battle-l** [comment]
你是不是用的训练好的模型，好像是不兼容，你用第一个75k那个试试
