### ISSUE TITLE
出现了新的问题

### ISSUE THREAD

**Issue by 123LIAO** [babysor/MockingBird#313]
输入框输入内容只能合成一次声音，再次输入则会合成失败，只能重启，是什么原因呢？报错信息如下
Error opening OutputStream: Unanticipated host error [PaErrorCode -9999]: '使用的设备标识号已超出本地系统范围。' [MME error 2]
Traceback (most recent call last):
  File "D:\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 331, in vocode
    self.ui.draw_embed(embed, name, "generated")
  File "D:\MockingBird-main\MockingBird-main\toolbox\ui.py", line 70, in draw_embed
    embed_ax.figure.canvas.draw()
  File "C:\Python38\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "C:\Python38\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\Python38\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Python38\lib\site-packages\matplotlib\figure.py", line 2796, in draw
    artists = self._get_draw_artists(renderer)
  File "C:\Python38\lib\site-packages\matplotlib\figure.py", line 238, in _get_draw_artists
    ax.apply_aspect()
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 1967, in apply_aspect
    self.set_xbound(x_trf.inverted().transform([x0, x1]))
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3564, in set_xbound
    self.set_xlim(sorted((lower, upper),
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3688, in set_xlim
    left = self._validate_converted_limits(left, self.convert_xunits)
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3605, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
Traceback (most recent call last):
  File "D:\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 331, in vocode
    self.ui.draw_embed(embed, name, "generated")
  File "D:\MockingBird-main\MockingBird-main\toolbox\ui.py", line 70, in draw_embed
    embed_ax.figure.canvas.draw()
  File "C:\Python38\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "C:\Python38\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\Python38\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Python38\lib\site-packages\matplotlib\figure.py", line 2796, in draw
    artists = self._get_draw_artists(renderer)
  File "C:\Python38\lib\site-packages\matplotlib\figure.py", line 238, in _get_draw_artists
    ax.apply_aspect()
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 1967, in apply_aspect
    self.set_xbound(x_trf.inverted().transform([x0, x1]))
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3564, in set_xbound
    self.set_xlim(sorted((lower, upper),
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3688, in set_xlim
    left = self._validate_converted_limits(left, self.convert_xunits)
  File "C:\Python38\lib\site-packages\matplotlib\axes\_base.py", line 3605, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

**Comment by babysor** [comment]
窗口大小问题

**Comment by 123LIAO** [comment]
> 窗口大小问题

请问一下该如何解决这个问题

**Comment by babysor** [comment]
拉大窗口..

**Comment by 123LIAO** [comment]
> 拉大窗口..

谢谢，解决了
