### ISSUE TITLE
在ubentu系统训练时，找不到train.txt目录

### ISSUE THREAD

**Issue by HuaHuaOfficial** [babysor/MockingBird#322]
如图。在windows端完全没问题，但上服务器就报错
(base) root@f7a701305fdd:~/data/MockingBird-main# python synthesizer_train.py 22 data/datasets_root/SV2TTS/synthesizer
Arguments:
    run_id:          22
    syn_dir:         data/datasets_root/SV2TTS/synthesizer
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    log_every:       200
    force_restart:   False
    hparams:         

Checkpoint path: synthesizer/saved_models/22/22.pt
Loading training data from: data/datasets_root/SV2TTS/synthesizer/train.txt
Using model: Tacotron
Using device: cuda

Initialising Tacotron Model...

Trainable Parameters: 32.869M

Loading weights at synthesizer/saved_models/22/22.pt
Tacotron weights loaded from step 0
Using inputs from:
        data/datasets_root/SV2TTS/synthesizer/train.txt
        data/datasets_root/SV2TTS/synthesizer/mels
        data/datasets_root/SV2TTS/synthesizer/embeds
Traceback (most recent call last):
  File "synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "/root/data/MockingBird-main/synthesizer/train.py", line 121, in train
    dataset = SynthesizerDataset(metadata_fpath, mel_dir, embed_dir, hparams)
  File "/root/data/MockingBird-main/synthesizer/synthesizer_dataset.py", line 12, in __init__
    with metadata_fpath.open("r", encoding="utf-8") as metadata_file:
  File "/root/miniconda3/lib/python3.8/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/root/miniconda3/lib/python3.8/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/datasets_root/SV2TTS/synthesizer/train.txt'
`

**Comment by HuaHuaOfficial** [comment]
![Uploading 屏幕截图 2022-01-07 143939.png…]()

**Comment by babysor** [comment]
一般都是路径问题 确认一下相对路径

**Comment by diaxia** [comment]
有没有安装教程？找了好久都是win的
