### ISSUE TITLE
我的mac m1所有都用的arm包运行起来闪退

### ISSUE THREAD

**Issue by absc** [babysor/MockingBird#328]
> Traceback (most recent call last):
  File "/Users/huyouwangzecai/Documents/项目/个人项目/声音项目/MockingBird-main/toolbox/ui.py", line 160, in setup_audio_devices
    sd.check_output_settings(device=device_namecheck, samplerate=sample_rate)
  File "/Users/huyouwangzecai/miniforge3/envs/muisc_copy/lib/python3.9/site-packages/sounddevice.py", line 691, in check_output_settings
    _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate))
  File "/Users/huyouwangzecai/miniforge3/envs/muisc_copy/lib/python3.9/site-packages/sounddevice.py", line 2736, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: <unprintable PortAudioError object>
这是我的报错内容，sounddevice check_output_settings方法运行不成功有了解的么

**Comment by mr-m0nst3r** [comment]
一样遇到这个问题。解决了吗？

**Comment by toimc** [comment]
```
Arguments:
    datasets_root:    test
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Warning: you do not have any of the recognized datasets in test.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
	aidatatang_200zh/corpus/dev
	aidatatang_200zh/corpus/test
	aishell3/test/wav
	magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| OpenStream @ 16000 returned: -9999: Unanticipated host error
||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| OpenStream @ 16000 returned: -9999: Unanticipated host error
Traceback (most recent call last):
  File "/Users/macos/Downloads/ai-voice/MockingBird/toolbox/ui.py", line 159, in setup_audio_devices
    sd.check_output_settings(device=device["name"], samplerate=sample_rate)
  File "/Users/macos/miniconda3/envs/pytorch_env/lib/python3.8/site-packages/sounddevice.py", line 691, in check_output_settings
    _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate))
  File "/Users/macos/miniconda3/envs/pytorch_env/lib/python3.8/site-packages/sounddevice.py", line 2736, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: <unprintable PortAudioError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "/Users/macos/Downloads/ai-voice/MockingBird/toolbox/__init__.py", line 76, in __init__
    self.setup_events()
  File "/Users/macos/Downloads/ai-voice/MockingBird/toolbox/__init__.py", line 113, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "/Users/macos/Downloads/ai-voice/MockingBird/toolbox/ui.py", line 164, in setup_audio_devices
    warn("Unsupported output device %s for the sample rate: %d \nError: %s" % (device["name"], sample_rate, str(e)))
  File "/Users/macos/miniconda3/envs/pytorch_env/lib/python3.8/site-packages/sounddevice.py", line 2220, in __str__
    hostname = query_hostapis(host_api)['name']
  File "/Users/macos/miniconda3/envs/pytorch_env/lib/python3.8/site-packages/sounddevice.py", line 640, in query_hostapis
    raise PortAudioError('Error querying host API {}'.format(index))
sounddevice.PortAudioError: Error querying host API -9979
```

一样的问题！

**Comment by hxqbeyond** [comment]
一样的问题 求解；打开就闪退

**Comment by hxqbeyond** [comment]
> Traceback (most recent call last): File "/Users/huyouwangzecai/Documents/项目/个人项目/声音项目/MockingBird-main/toolbox/ui.py", line 160, in setup_audio_devices sd.check_output_settings(device=device_namecheck, samplerate=sample_rate) File "/Users/huyouwangzecai/miniforge3/envs/muisc_copy/lib/python3.9/site-packages/sounddevice.py", line 691, in check_output_settings _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate)) File "/Users/huyouwangzecai/miniforge3/envs/muisc_copy/lib/python3.9/site-packages/sounddevice.py", line 2736, in _check raise PortAudioError(errormsg, err, hosterror_info) sounddevice.PortAudioError: 这是我的报错内容，sounddevice check_output_settings方法运行不成功有了解的么

后面解决了吗

**Comment by absc** [comment]
> > Traceback (most recent call last): File "/Users/huyouwangzecai/Documents/项目/个人项目/声音项目/MockingBird-main/toolbox/ui.py", line 160, in setup_audio_devices sd.check_output_settings(device=device_namecheck, samplerate=sample_rate) File "/Users/huyouwangzecai/miniforge3/envs/muisc_copy/lib/python3.9/site-packages/sounddevice.py", line 691, in check_output_settings _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate)) File "/Users/huyouwangzecai/miniforge3/envs/muisc_copy/lib/python3.9/site-packages/sounddevice.py", line 2736, in _check raise PortAudioError(errormsg, err, hosterror_info) sounddevice.PortAudioError: 这是我的报错内容，sounddevice check_output_settings方法运行不成功有了解的么
> 
> 后面解决了吗

全部找m1专用的arm架构包， 不要用x86架构包，就可以正常运行

**Comment by Matrix-X** [comment]
Arguments:
    datasets_root:          test
    vc_mode:                False
    enc_models_dir:         encoder/saved_models
    syn_models_dir:         synthesizer/saved_models
    voc_models_dir:         vocoder/saved_models
    extractor_models_dir:   ppg_extractor/saved_models
    convertor_models_dir:   ppg2mel/saved_models
    cpu:                    False
    seed:                   None
    no_mp3_support:         False

Warning: you do not have any of the recognized datasets in test 
Please note use 'E:\datasets' as root path instead of 'E:\datasetsidatatang_200zh\corpus	est' as an example .
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
	aidatatang_200zh/corpus
	aishell3/test/wav
	magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| OpenStream @ 16000 returned: -9999: Unanticipated host error
||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| OpenStream @ 16000 returned: -9999: Unanticipated host error
Traceback (most recent call last):
  File "/Library/WebServer/Documents/Projects/PowerAI/Voice/MockingBird/toolbox/ui.py", line 159, in setup_audio_devices
    sd.check_output_settings(device=device["name"], samplerate=sample_rate)
  File "/Users/michaelhu/miniforge3/envs/voice-clone/lib/python3.9/site-packages/sounddevice.py", line 691, in check_output_settings
    _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate))
  File "/Users/michaelhu/miniforge3/envs/voice-clone/lib/python3.9/site-packages/sounddevice.py", line 2736, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: <unprintable PortAudioError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/WebServer/Documents/Projects/PowerAI/Voice/MockingBird/demo_toolbox.py", line 49, in <module>
    Toolbox(**vars(args))
  File "/Library/WebServer/Documents/Projects/PowerAI/Voice/MockingBird/toolbox/__init__.py", line 80, in __init__
    self.setup_events()
  File "/Library/WebServer/Documents/Projects/PowerAI/Voice/MockingBird/toolbox/__init__.py", line 126, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "/Library/WebServer/Documents/Projects/PowerAI/Voice/MockingBird/toolbox/ui.py", line 164, in setup_audio_devices
    warn("Unsupported output device %s for the sample rate: %d \nError: %s" % (device["name"], sample_rate, str(e)))
  File "/Users/michaelhu/miniforge3/envs/voice-clone/lib/python3.9/site-packages/sounddevice.py", line 2220, in __str__
    hostname = query_hostapis(host_api)['name']
  File "/Users/michaelhu/miniforge3/envs/voice-clone/lib/python3.9/site-packages/sounddevice.py", line 640, in query_hostapis
    raise PortAudioError('Error querying host API {}'.format(index))
sounddevice.PortAudioError: Error querying host API -9979


Mac上安装参考 https://r0fus0d.blog.ffffffff0x.com/post/m1-mockingbird/#安装-ffmpeg

同样的问题，请问该怎么解决
