### ISSUE TITLE
小白求助：Mocking Bird GUI运行python demo_toolbox.py的时候报错

### ISSUE THREAD

**Issue by axiguagua** [babysor/MockingBird#333]
Mocking Bird GUI运行python demo_toolbox.py的时候报错，显示没有“torch”module
D:\MockingBird jiaocheng\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
File "D:\MockingBird jiaocheng\MockingBird-main\demo_toolbox.py", line 2, in <module>
from toolbox import Toolbox
File "D:\MockingBird jiaocheng\MockingBird-main\toolbox\__init__.py", line 1, in <module>
from toolbox.ui import UI
File "D:\MockingBird jiaocheng\MockingBird-main\toolbox\ui.py", line 7, in <module>
from encoder.inference import plot_embedding_as_heatmap
File "D:\MockingBird jiaocheng\MockingBird-main\encoder\inference.py", line 2, in <module>
from encoder.model import SpeakerEncoder
File "D:\MockingBird jiaocheng\MockingBird-main\encoder\model.py", line 5, in <module>
from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'

**Comment by axiguagua** [comment]
请问有大佬指导下吗ww

**Comment by MrWeijing** [comment]
pytorch没装

**Comment by JOJOda123** [comment]
有没有闪退呢，我之前启动GUI闪退了然后，按照作者这个方法就可以了，链接：https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF
