### ISSUE TITLE
【求助】预训练后没有生成任何新数据

### ISSUE THREAD

**Issue by QSshuyunmu** [babysor/MockingBird#352]
刚开始时是运行中有显示“页面文件太小”出错，但是在调整pagefile.sys之后，仍然没产生任何新文件。
前半段是这样的
F:\zhivoice\MockingBird-main>python pre.py F:/zhivoice -d aidatatang_200zh -n 6
Using data from:
    F:\zhivoice\aidatatang_200zh\corpus\train
aidatatang_200zh:   0%|                                                                    | 0/1 [00:00<?, ?speakers/s]no wordS
no wordS
no wordS
no wordS
no wordS
no wordS
no wordS
no wordS
中间全部都是 
no wordS
后半段是这样的
no wordS
no wordS
no wordS
no wordS
no wordS
no wordS
no wordS
aidatatang_200zh: 100%|████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.15s/speakers]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "F:\zhivoice\MockingBird-main\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "F:\zhivoice\MockingBird-main\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

F:\zhivoice\MockingBird-main>
步骤都是按照教程一步步来的，恳请大佬指点一下，花了好长时间卡在这里实在没办法了

**Comment by babysor** [comment]
教程里面有提到 解压 aidatatang_200zh\corpus\train 下的压缩文件，你做了吗？

**Comment by sakuraee** [comment]
我也遇到了一样的问题楼主解决了吗，train文件夹下是解压了的

**Comment by QiFuChina** [comment]
> 教程里面有提到 解压 aidatatang_200zh\corpus\train 下的压缩文件，你做了吗？

请问这个需要下载那个18G的原始数据集么？文档里提到解压所有的压缩文件，但是我看视频里是把处理后的数据集复制进去直接预处理和训练，并替换模型
有点疑惑，没搞明白

**Comment by sunnylawliet** [comment]
我也出现这个错,在aidatatang_200zh\corpus\train下面又新建了文件夹就行了
