### ISSUE TITLE
提示无法正常运行

### ISSUE THREAD

**Issue by zhang065** [babysor/MockingBird#368]
我换了一台电脑继续运行运行以下命令：python C:\MockingBird-main\demo_toolbox.py -d .\samples后提示：
Traceback (most recent call last):
  File "C:\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\MockingBird-main\toolbox\ui.py", line 16, in <module>
    import umap
ModuleNotFoundError: No module named 'umap'
于是我又换了种说法:python C:\MockingBird-main\demo_toolbox.py又提示：
Traceback (most recent call last):
  File "C:\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\MockingBird-main\toolbox\ui.py", line 16, in <module>
    import umap
ModuleNotFoundError: No module named 'umap'
这台新机器是双显版本1.Intel iris Xe 11代酷睿搭载 2.NVDIA GeForce MX350 CUDA版本为11.6.99
对于小白来说，请问如何解决？？？

**Comment by zhang065** [comment]
python版本为3.9.10

**Comment by babysor** [comment]
可以尝试运行 pip install umap
不然的话建议回滚python到3.8

**Comment by zhang065** [comment]
谢谢
