### ISSUE TITLE
不能运行pre.py 怎么办呀大佬们

### ISSUE THREAD

**Issue by 183954477** [babysor/MockingBird#371]
D:\MockingBird-main\MockingBird-main>python pre.py D:\shujuchuli
Using data from:
    D:\shujuchuli\aidatatang_200zh\corpus\train
Traceback (most recent call last):
  File "pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "D:\MockingBird-main\MockingBird-main\synthesizer\preprocess.py", line 64
, in preprocess_dataset
    for v in dict_transcript:
  File "D:\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 10: invalid
 start byte

**Comment by babysor** [comment]
https://github.com/babysor/MockingBird/wiki/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF
