### ISSUE TITLE
无法读取WAV或MP3音频

### ISSUE THREAD

**Issue by Perlistan** [babysor/MockingBird#374]
```
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "E:\MockingBird\toolbox\__init__.py", line 103, in <lambda>
    func = lambda: self.load_from_browser(self.ui.browse_file())
  File "E:\MockingBird\toolbox\__init__.py", line 170, in load_from_browser
    wav = Synthesizer.load_preprocess_wav(fpath)
  File "E:\MockingBird\synthesizer\inference.py", line 146, in load_preprocess_wav
    wav = librosa.load(str(fpath), hparams.sample_rate)[0]
TypeError: load() takes 1 positional argument but 2 were given
```

这该如何处理？

**Comment by JinkelaP** [comment]
我第一次使用的时候没这个问题，后来借着学习这个项目入坑了python，过了两天反而出现GUI无响应的问题。重装python之后，就变成这个问题了，不知道是不是因为有什么库冲突了。。。。

**Comment by chenxij8** [comment]
我也是这个问题！！

**Comment by babysor** [comment]
#372
