### ISSUE TITLE
AttributeError: 'HParams' object has no attribute 'dumpJson'突然出现的问题

### ISSUE THREAD

**Issue by skal-h** [babysor/MockingBird#401]
本来好好地训练到了100k，但是中间暂停了一下试了一下模型，然后重新开始训练报错了
Traceback (most recent call last):
  File "D:\Mocking Bird\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "D:\Mocking Bird\MockingBird-main\synthesizer\train.py", line 85, in train
    hparams.dumpJson(weights_fpath.parent.joinpath(run_id).with_suffix(".json"))
AttributeError: 'HParams' object has no attribute 'dumpJson'

没学过python所以看不懂 ：( 求教5555

**Comment by skal-h** [comment]
已解决，我把两天前 train.py 的添加更新删了…………

                # Try to scan config file
        model_config_fpaths = list(weights_fpath.parent.rglob("*.json"))
        if len(model_config_fpaths)>0 and model_config_fpaths[0].exists():
            with model_config_fpaths[0].open("r", encoding="utf-8") as f:
                hparams.loadJson(json.load(f))
        else:  # save a config
            hparams.dumpJson(weights_fpath.parent.joinpath(run_id).with_suffix(".json"))

就是这一段
