### ISSUE TITLE
Mac m1 启动GUI闪退

### ISSUE THREAD

**Issue by hxqbeyond** [babysor/MockingBird#408]
python3 demo_toolbox.py
-------------------------------------------------------
Arguments:
    datasets_root:    None
    enc_models_dir:   encoder/saved_models
    syn_models_dir:   synthesizer/saved_models
    voc_models_dir:   vocoder/saved_models
    cpu:              False
    seed:             None
    no_mp3_support:   False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
	LibriSpeech/dev-clean
	LibriSpeech/dev-other
	LibriSpeech/test-clean
	LibriSpeech/test-other
	LibriSpeech/train-clean-100
	LibriSpeech/train-clean-360
	LibriSpeech/train-other-500
	LibriTTS/dev-clean
	LibriTTS/dev-other
	LibriTTS/test-clean
	LibriTTS/test-other
	LibriTTS/train-clean-100
	LibriTTS/train-clean-360
	LibriTTS/train-other-500
	LJSpeech-1.1
	VoxCeleb1/wav
	VoxCeleb1/test_wav
	VoxCeleb2/dev/aac
	VoxCeleb2/test/aac
	VCTK-Corpus/wav48
	aidatatang_200zh/corpus/dev
	aidatatang_200zh/corpus/test
	aishell3/test/wav
	magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| OpenStream @ 16000 returned: -9999: Unanticipated host error
||PaMacCore (AUHAL)|| AUHAL component not found.||PaMacCore (AUHAL)|| OpenStream @ 16000 returned: -9999: Unanticipated host error
Traceback (most recent call last):
  File "/Users/***/work/demo/MockingBird/toolbox/ui.py", line 159, in setup_audio_devices
    sd.check_output_settings(device=device["name"], samplerate=sample_rate)
  File "/Users/***/miniconda3/lib/python3.9/site-packages/sounddevice.py", line 691, in check_output_settings
    _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate))
  File "/Users/***/miniconda3/lib/python3.9/site-packages/sounddevice.py", line 2736, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: <unprintable PortAudioError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/***/work/demo/MockingBird/demo_toolbox.py", line 43, in <module>
    Toolbox(**vars(args))
  File "/Users/***/work/demo/MockingBird/toolbox/__init__.py", line 76, in __init__
    self.setup_events()
  File "/Users/***/work/demo/MockingBird/toolbox/__init__.py", line 113, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "/Users/***/work/demo/MockingBird/toolbox/ui.py", line 164, in setup_audio_devices
    warn("Unsupported output device %s for the sample rate: %d \nError: %s" % (device["name"], sample_rate, str(e)))
  File "/Users/***/miniconda3/lib/python3.9/site-packages/sounddevice.py", line 2220, in __str__
    hostname = query_hostapis(host_api)['name']
  File "/Users/***/miniconda3/lib/python3.9/site-packages/sounddevice.py", line 640, in query_hostapis
    raise PortAudioError('Error querying host API {}'.format(index))
sounddevice.PortAudioError: Error querying host API -9979

**Comment by clstech** [comment]
请问有解决办法吗
