### ISSUE TITLE
【小白提问】AttributeError: module 'distutils' has no attribute 'version' 怎么解？？这个问题困扰了一下午都没能解决

### ISSUE THREAD

**Issue by arzmi** [babysor/MockingBird#409]
D:\MockingBird-main>python synthesizer_train.py man D:\制作数据集\SV2TTS\synthesizer
Traceback (most recent call last):
  File "synthesizer_train.py", line 2, in <module>
    from synthesizer.train import train
  File "D:\MockingBird-main\synthesizer\train.py", line 5, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\VisionMNext\AppData\Roaming\Python\Python36\site-packages\torch\utils\tensorboard\__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

**Comment by arzmi** [comment]
经过本人努力，发现 在 C:\Users\VisionMNext\AppData\Roaming\Python\Python36\site-packages\torch\utils\tensorboard 
__init__.py 
文件中加入 
from distutils.version import LooseVersion。
锁定位置就OK了
原理是什么有人能教一下吗

**Comment by arzmi** [comment]
你们训练了多久才出图，我用了半个小时

**Comment by flysmart** [comment]
请问你用的是哪个数据集？大小是多少？

**Comment by babysor** [comment]
> 你们训练了多久才出图，我用了半个小时
比较快了

**Comment by arzmi** [comment]
> > 你们训练了多久才出图，我用了半个小时
> > 比较快了

还好，我现在20分钟一张图，训练了8个小时从0.8降到0.62

**Comment by JerryZRF** [comment]
> 你们训练了多久才出图，我用了半个小时

我练了24小时还没出图
{| Epoch: 2/2 (4130/10207) | Loss: 0.4730 | 0.66 steps/s | Step: 54k | }

**Comment by babysor** [comment]
看错文件夹了吧？如果是得话麻烦关闭一下issue
