### ISSUE TITLE
synthesizer跑到到1500步就出错，有高手知道是怎么回事吗

### ISSUE THREAD

**Issue by lijielijie** [babysor/MockingBird#418]
下面是日志：
{| Epoch: 143/910 (10/11) | Loss: 0.3434 | 1.1 steps/s | Step: 1k | }{| Epoch: 143/910 (11/11) | Loss: 0.3442 | 1.1 steps/s | Step: 1k | }
{| Epoch: 144/910 (11/11) | Loss: 0.3435 | 1.1 steps/s | Step: 1k | }
{| Epoch: 145/910 (2/11) | Loss: 0.3433 | 1.1 steps/s | Step: 1k | }Traceback (most recent call last):
  File "D:\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "D:\MockingBird-main\synthesizer\train.py", line 201, in train
    loss.backward()
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by babysor** [comment]
目前发现这个问题没有好得解决方法，跟驱动稳定性有关，可以把batchsize调小一点看可能是否会改善。

**Comment by lijielijie** [comment]
> 目前发现这个问题没有好得解决方法，跟驱动稳定性有关，可以把batchsize调小一点看可能是否会改善。

谢谢，我昨晚从12改成8果然不报错了。
但是又出现一个问题，昨天速度还是1.3steps/s, 
【{| Epoch: 143/30000 (10/11) | Loss: 0.5434 | 1.3 steps/s | Step: 55k | }】

今天再打开怎么只有0.67steps/s了
【{| Epoch: 34/16500 (4/4) | Loss: 0.5018 | 0.67 steps/s | Step: 94k | }】

**Comment by lijielijie** [comment]
> 我这么设置，它会在不同的步数下使用不同的batchsize吗
![image](https://user-images.githubusercontent.com/20817575/156795108-ef775a1e-3854-41eb-8398-3b4c49a0b5c0.png)

**Comment by babysor** [comment]
> > 目前发现这个问题没有好得解决方法，跟驱动稳定性有关，可以把batchsize调小一点看可能是否会改善。
> 
> 谢谢，我昨晚从12改成8果然不报错了。 但是又出现一个问题，昨天速度还是1.3steps/s, 【{| Epoch: 143/30000 (10/11) | Loss: 0.5434 | 1.3 steps/s | Step: 55k | }】
> 
> 今天再打开怎么只有0.67steps/s了 【{| Epoch: 34/16500 (4/4) | Loss: 0.5018 | 0.67 steps/s | Step: 94k | }】

是的，建议阶梯调大，而不是调小

**Comment by lijielijie** [comment]
> 0.67 steps/s

总是 0.67 steps/s，这个速度怎么调大呀？

**Comment by babysor** [comment]
> > 0.67 steps/s
> 
> 总是 0.67 steps/s，这个速度怎么调大呀？

这里有效速度约是这个数字*batchsize. 完全看gpu算力 没法手动调大

**Comment by babysor** [comment]
发现是个bug，正在修复，你可以先把saved model下的json删掉，
