### ISSUE TITLE
执行python demo_toolbox.py报错

### ISSUE THREAD

**Issue by imi-123** [babysor/MockingBird#428]
执行python demo_toolbox.py报错，

PS C:\MockingBird-main (1)\MockingBird-main> python demo_toolbox.py
Traceback (most recent call last):
  File "C:\MockingBird-main (1)\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\MockingBird-main (1)\MockingBird-main\toolbox\__init__.py", line 6, in <module>
    import ppg_extractor as extractor
  File "C:\MockingBird-main (1)\MockingBird-main\ppg_extractor\__init__.py", line 8, in <module>
    from .encoder.conformer_encoder import ConformerEncoder
  File "C:\MockingBird-main (1)\MockingBird-main\ppg_extractor\encoder\conformer_encoder.py", line 28, in <module>
    from .subsampling import Conv2dNoSubsampling, Conv2dSubsampling
  File "C:\MockingBird-main (1)\MockingBird-main\ppg_extractor\encoder\subsampling.py", line 11, in <module>
    from espnet.nets.pytorch_backend.transformer.embedding import PositionalEncoding
ModuleNotFoundError: No module named 'espnet'

之后我执行pip install espnet也出现了错误，找了很久都没有找到解决方法，希望可以得到一些帮助。

**Comment by Kepler-II** [comment]
有一种可能，运行pip install espnet时是不是出现了“安装pyworld的环节”失败的情况？
如果是这样的话，似乎需要先下载visual_studio再重试pip install espnet
我用的是anaconda，在下载了visual_studio之后仍然报错，于是重装了anaconda之后再pip install pyworld或者pip install espnet就成功了（费了好大功夫）

**Comment by babysor** [comment]
已修复：依赖没有剥离干净，你拉下最新代码 git pull origin/main 试试

**Comment by imi-123** [comment]
> 已修复：依赖没有剥离干净，你拉下最新代码 git pull origin/main 试试

已经解决了，感谢

**Comment by cddldg** [comment]
visual_studio 安装了以后，一定要重启一下电脑，我的就是这么解决的 o(╥﹏╥)o
