### ISSUE TITLE
【长期】学术/论文讨论/训练分析

### ISSUE THREAD

**Issue by babysor** [babysor/MockingBird#438]

**Comment by Chopin68** [comment]
留下第一条！

**Comment by DQ2020scut** [comment]
请问克隆出来的语音有什么办法可以保存为wav文件吗

**Comment by babysor** [comment]
> 请问克隆出来的语音有什么办法可以保存为wav文件吗

这个有点不太扣题，我回了你的issue了

**Comment by GUGUGU-01** [comment]
> 

我也想知道 需要用其他软件再录下来吗 感觉好麻烦

**Comment by babysor** [comment]
> > 
> 
> 我也想知道 需要用其他软件再录下来吗 感觉好麻烦

软件界面就有直接导出保存的

**Comment by pxdawn** [comment]
> > 
> 
> 我也想知道 需要用其他软件再录下来吗 感觉好麻烦

Export按钮

**Comment by MarkIzhao** [comment]
Traceback (most recent call last):
  File "G:\Vioce\MockingBird\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "G:\Vioce\MockingBird\synthesizer\train.py", line 215, in train
    optimizer.step()
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 157, in step
    adam(params_with_grad,
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 213, in adam
    func(params,
  File "C:\Users\Mark\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.
请问如何解决

> > > 
> > 
> > 
> > 我也想知道 需要用其他软件再录下来吗 感觉好麻烦
> 
> 软件界面就有直接导出保存的
