### ISSUE TITLE
使用WaveRNN报错

### ISSUE THREAD

**Issue by JerryZRF** [babysor/MockingBird#445]
报错如下
> Traceback (most recent call last):
  File "D:\Apps\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Apps\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Apps\Anaconda3\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "D:\Apps\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Apps\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Apps\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Apps\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\Jerry\Documents\Jerry\MockingBird-main\web\__init__.py", line 118, in synthesize
    write(out, sample_rate, wav.astype(np.float32))
AttributeError: 'tuple' object has no attribute 'astype'
127.0.0.1 - - [2022-03-09 14:13:44] "POST /api/synthesize HTTP/1.1" 500 426 14.539417

**Comment by huangxinping** [comment]
@JerryZRF 你解决了吗？
