### ISSUE TITLE
无法启动web

### ISSUE THREAD

**Issue by xkong1112** [babysor/MockingBird#446]
`Loaded synthesizer models: 0
Loaded encoder "pretrained.pt" trained to step 1594501
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Traceback (most recent call last):
  File "C:\Users\98212\MockingBird\web.py", line 6, in <module>
    app = webApp()
  File "C:\Users\98212\MockingBird\web\__init__.py", line 35, in webApp
    gan_vocoder.load_model(Path("vocoder/saved_models/pretrained/g_hifigan.pt"))
TypeError: load_model() missing 1 required positional argument: 'config_fpath'`

**Comment by JerryZRF** [comment]
下载最新版本试试
https://github.com/babysor/MockingBird/archive/refs/heads/main.zip

**Comment by king010699** [comment]
最新版本也有同樣的問題，還是不能啟動web

**Comment by xkong1112** [comment]
好像还是一样
(base) PS C:\Users\98212> cd .\MockingBird-main\
(base) PS C:\Users\98212\MockingBird-main> python web.py
Loaded synthesizer models: 0
Loaded encoder "pretrained.pt" trained to step 1594501
Building Wave-RNN
Trainable Parameters: 4.481M
Loading model weights at vocoder\saved_models\pretrained\pretrained.pt
Traceback (most recent call last):
  File "C:\Users\98212\MockingBird-main\web.py", line 6, in <module>
    app = webApp()
  File "C:\Users\98212\MockingBird-main\web\__init__.py", line 35, in webApp
    gan_vocoder.load_model(Path("vocoder/saved_models/pretrained/g_hifigan.pt"))
TypeError: load_model() missing 1 required positional argument: 'config_fpath'

**Comment by JerryZRF** [comment]
> 好像还是一样 (base) PS C:\Users\98212> cd .\MockingBird-main (base) PS C:\Users\98212\MockingBird-main> python web.py Loaded synthesizer models: 0 Loaded encoder "pretrained.pt" trained to step 1594501 Building Wave-RNN Trainable Parameters: 4.481M Loading model weights at vocoder\saved_models\pretrained\pretrained.pt Traceback (most recent call last): File "C:\Users\98212\MockingBird-main\web.py", line 6, in app = webApp() File "C:\Users\98212\MockingBird-main\web__init__.py", line 35, in webApp gan_vocoder.load_model(Path("vocoder/saved_models/pretrained/g_hifigan.pt")) TypeError: load_model() missing 1 required positional argument: 'config_fpath'

把vocoder\hifigan\inference.py第22行从`def load_model(weights_fpath, config_fpath, verbose=True):`改成`def load_model(weights_fpath, config_fpath="./vocoder/hifigan/config_16k_.json", verbose=True):`

**Comment by babysor** [comment]
我更正代码一下，感谢楼上
