### ISSUE TITLE
在运行工具箱合成声音时出现了这个提示是怎么回事呀

### ISSUE THREAD

**Issue by 7zyz7** [babysor/MockingBird#450]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\PythonProject\Pytorch\MockingBird_main\web\__init__.py", line 108, in synthesize
    specs = current_synt.synthesize_spectrograms(texts, embeds)
  File "D:\PythonProject\Pytorch\MockingBird_main\synthesizer\inference.py", line 128, in synthesize_spectrograms
    _, mels, alignments = self._model.generate(chars, speaker_embeddings, style_idx=style_idx, min_stop_token=min_stop_token, steps=steps)
  File "D:\PythonProject\Pytorch\MockingBird_main\synthesizer\models\tacotron.py", line 448, in generate
    encoder_seq = self.encoder(x, speaker_embedding)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PythonProject\Pytorch\MockingBird_main\synthesizer\models\tacotron.py", line 41, in forward
    x = self.cbhg(x)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PythonProject\Pytorch\MockingBird_main\synthesizer\models\tacotron.py", line 138, in forward
    c = conv(x) # Convolution
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\PythonProject\Pytorch\MockingBird_main\synthesizer\models\tacotron.py", line 84, in forward
    x = self.conv(x)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ProgramData\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\conv.py", line 298, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

直接用的大佬的模型

**Comment by babysor** [comment]
pytorch安装正常了吗？显卡是不是不支持cuda

**Comment by 7zyz7** [comment]
应该是没有问题，之前自己训练模型的时候也用的cuda训练成功了，这次不知道为什么




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 晚上7:12
收件人: ***@***.***&gt;; 
抄送: "Yuzhu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [babysor/MockingBird] 在运行工具箱合成声音时出现了这个提示是怎么回事呀 (Issue #450)





 
pytorch安装正常了吗？显卡是不是不支持cuda
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by babysor** [comment]
看报错，是pytorch出了问题，每次必现吗？

**Comment by 7zyz7** [comment]
不是欸，使用了您发布的老版本就没有问题，我运行新版本会报这个错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 晚上7:29
收件人: ***@***.***&gt;; 
抄送: "Yuzhu ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [babysor/MockingBird] 在运行工具箱合成声音时出现了这个提示是怎么回事呀 (Issue #450)





 
看报错，是pytorch出了问题，每次必现吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
