### ISSUE TITLE
【小白提问】没有GPU的机器总是显示没有torch包

### ISSUE THREAD

**Issue by momoares** [babysor/MockingBird#456]
**Summary[问题简述（一句话）]
没有GPU的机器总是显示没有torch包，如题，电脑没有英伟达显卡，故在安装pytorch时选择了CPU版，如图。
在环境安装后，python环境下输入import pytorch不报错，但输入torch.cuda.is_available（）返回False
尝试安装其余版本（如新手教程中版本，仍然如此）
—其余操作都完成的情况下，在主程序目录下
尝试强行python demo_toolbox.py -d .\samples，报错如下..不知道该怎么解决了

![image](https://user-images.githubusercontent.com/101468450/158357520-d8897889-95dd-4df3-be2a-4a0e4f8040a9.png)

D:\MockingBird-main>python demo_toolbox.py -d .\samples
Traceback (most recent call last):
  File "D:\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\MockingBird-main\toolbox\ui.py", line 7, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "D:\MockingBird-main\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "D:\MockingBird-main\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
ModuleNotFoundError: No module named 'torch'

**Comment by momoares** [comment]
谢谢！已经解决了，重新装了一遍就不报错了...
