### ISSUE TITLE
小白提问，有大佬知道这是怎么回事吗？

### ISSUE THREAD

**Issue by zhangzixin1221** [babysor/MockingBird#461]
{| ████████████████ 19000/19200 | Batch Size: 2 | Gen Rate: 1.5kHz | }[2022-03-17 19:46:31,246] ERROR in app: Exception on /api/synthesize [POST]
Traceback (most recent call last):
  File "C:\Users\29238\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\29238\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\29238\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_restx\api.py", line 672, in error_router
    return original_handler(e)
  File "C:\Users\29238\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\29238\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\MockingBird-main\web\__init__.py", line 118, in synthesize
    write(out, sample_rate, wav.astype(np.float32))
AttributeError: 'tuple' object has no attribute 'astype'
127.0.0.1 - - [2022-03-17 19:46:31] "POST /api/synthesize HTTP/1.1" 500 426 15.250402

**Comment by babysor** [comment]
Fixed in main branch
