### ISSUE TITLE
点击合成器报错

### ISSUE THREAD

**Issue by XSXIEYCH** [babysor/MockingBird#483]
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([66, 512]).

这个错误怎么解决，设置了use_gst = False,已经消除几个了，还有一个，怎么解决呢

**Comment by babysor** [comment]
#37

**Comment by XSXIEYCH** [comment]
感谢反馈，但是我硬是没找到这个文件
synthesizer/utils/symbols.py
![Uploading image.png…]()

**Comment by XSXIEYCH** [comment]
![Uploading image.png…]()
附上详细错误
Traceback (most recent call last):
  File "C:\Users\91096\Desktop\MyFile\smilatevoices\speekChinese\toolbox\__init__.py", line 262, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds, style_idx=int(self.ui.style_slider.value()), min_stop_token=min_token, steps=int(self.ui.length_slider.value())*200)
  File "C:\Users\91096\Desktop\MyFile\smilatevoices\speekChinese\synthesizer\inference.py", line 93, in synthesize_spectrograms
    self.load()
  File "C:\Users\91096\Desktop\MyFile\smilatevoices\speekChinese\synthesizer\inference.py", line 71, in load
    self._model.load(self.model_fpath, self.device)
  File "C:\Users\91096\Desktop\MyFile\smilatevoices\speekChinese\synthesizer\models\tacotron.py", line 547, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "C:\Users\91096\Envs\python37\lib\site-packages\torch\nn\modules\module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([75, 512]).
