### ISSUE TITLE
导入社区模型后无法进行训练 报错RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3

### ISSUE THREAD

**Issue by 584761274** [babysor/MockingBird#492]
![image](https://user-images.githubusercontent.com/75121140/161871959-0c6d4767-ccca-4224-827a-b19374f2f23c.png)
C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1933: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "E:\MockingBird-main\synthesizer\train.py", line 208, in train
    optimizer.step()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\adam.py", line 141, in step
    F.adam(params_with_grad,
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\optim\_functional.py", line 97, in adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3

**Comment by 584761274** [comment]
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for gst.stl.attention.W_query.weight: copying a param with shape torch.Size([512, 256]) from checkpoint, the shape in current model is torch.Size([512, 512]).
修改后出现另一问题

**Comment by 584761274** [comment]
重新下载main后 已解决
