### ISSUE TITLE
I need Help/我需要帮助

### ISSUE THREAD

**Issue by kon75943** [babysor/MockingBird#513]
I want to use mockingbird, but now I'm in trouble. Please help me!
我想用mockingbird，但现在我遇到麻烦了。请帮帮我！

C:\Users\Administrator\Desktop\Real-Time-Voice-Cloning-master\encoder\audio.py:13: UserWarning: Unable to import 'webrtcvad'. This package enables noise removal and is recommended.
  warn("Unable to import 'webrtcvad'. This package enables noise removal and is recommended.")
Arguments:
    datasets_root:   None
    models_dir:      saved_models
    cpu:             False
    seed:            None

Downloading encoder.pt: 0.00B [00:00, ?B/s]
Downloading synthesizer.pt: 0.00B [00:00, ?B/s]
Downloading vocoder.pt: 0.00B [00:00, ?B/s]

self.run()

  File "C:\ProgramData\Anaconda3\envs\ai\lib\threading.py", line 910, in run
  File "C:\ProgramData\Anaconda3\envs\ai\lib\threading.py", line 910, in run
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ai\lib\threading.py", line 973, in _bootstrap_inner
            self.run()self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\threading.py", line 910, in run

self._target(*self._args, **self._kwargs)  File "C:\Users\Administrator\Desktop\Real-Time-Voice-Cloning-master\utils\default_models.py", line 30, in download

          File "C:\Users\Administrator\Desktop\Real-Time-Voice-Cloning-master\utils\default_models.py", line 30, in download
urllib.request.urlretrieve(url, filename=target, reporthook=t.update_to)self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\Real-Time-Voice-Cloning-master\utils\default_models.py", line 30, in download
urllib.request.urlretrieve(url, filename=target, reporthook=t.update_to)

  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 239, in urlretrieve
    urllib.request.urlretrieve(url, filename=target, reporthook=t.update_to)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 239, in urlretrieve
      File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 239, in urlretrieve
        with contextlib.closing(urlopen(url, data)) as fp:with contextlib.closing(urlopen(url, data)) as fp:with contextlib.closing(urlopen(url, data)) as fp:

  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 214, in urlopen

  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 214, in urlopen
      File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 517, in open
return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 517, in open
return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 517, in open
            response = self._open(req, data)response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 534, in _open

response = self._open(req, data)
      File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 494, in _call_chain
result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 534, in _open
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 1389, in https_open
result = func(*args)
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 1389, in https_open
result = self._call_chain(self.handle_open, protocol, protocol +
        return self.do_open(http.client.HTTPSConnection, req,  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 494, in _call_chain

      File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 1349, in do_open
return self.do_open(http.client.HTTPSConnection, req,
  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 1349, in do_open
raise URLError(err)result = func(*args)

urllib.error    .  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 1389, in https_open
URLErrorraise URLError(err):     <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应 ，连接尝试失败。>return self.do_open(http.client.HTTPSConnection, req,

urllib.error.  File "C:\ProgramData\Anaconda3\envs\ai\lib\urllib\request.py", line 1349, in do_open
URLError    : raise URLError(err)<urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应 ，连接尝试失败。>

urllib.error.Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Real-Time-Voice-Cloning-master\demo_toolbox.py", line 34, in <module>
URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
    ensure_default_models(args.models_dir)
  File "C:\Users\Administrator\Desktop\Real-Time-Voice-Cloning-master\utils\default_models.py", line 54, in ensure_default_models
    assert target_path.exists() and target_path.stat().st_size == size, \
AssertionError: Download for encoder.pt failed. You may download models manually instead.
https://drive.google.com/drive/folders/1fU6umc5uQAVR2udZdHX-lDgXYzTyqG_j

Please help me!
请帮帮我！

**Comment by kon75943** [comment]
https://drive.google.com/drive/folders/1fU6umc5uQAVR2udZdHX-lDgXYzTyqG_j I can't download the content in this website
