### ISSUE TITLE
使用hifigan_24k报错 KeyError: 'model_state'

### ISSUE THREAD

**Issue by chn-lee-yumi** [babysor/MockingBird#521]
**Summary[问题简述（一句话）]**
Vocoder使用hifigan_24k报错 KeyError: 'model_state'，输出为杂音。使用pretrained或g_hifigan则正常。

**Env & To Reproduce[复现与环境]**
模型从readme的百度网盘下载
版本为最新的main分支。
从百度网盘下载模型放入对应目录后，vocoder选择hifigan_24k的时候就会报错。但是点击生成仍然可以正常运行，只是出来的都是杂音。

**Screenshots[截图（如有）]**
```
Traceback (most recent call last):
  File "/Users/xxx/Files/MockingBird/toolbox/__init__.py", line 467, in init_vocoder
    vocoder.load_model(model_fpath, model_config_fpath)
  File "/Users/xxx/Files/MockingBird/vocoder/wavernn/inference.py", line 37, in load_model
    _model.load_state_dict(checkpoint['model_state'])
KeyError: 'model_state'
```

![image](https://user-images.githubusercontent.com/20398519/165456129-295f6b4b-6d29-4377-8229-9f0ca60bfdec.png)

**Comment by babysor** [comment]
这个文件应该还伴随一个config文件，要一起下载

**Comment by chn-lee-yumi** [comment]
> 这个文件应该还伴随一个config文件，要一起下载

config文件是有的：
<img width="668" alt="image" src="https://user-images.githubusercontent.com/20398519/166140539-a185c0c9-3f81-4642-96b8-db89b71778f4.png">

**Comment by babysor** [comment]
我这边可以复现，英文的话会比较好，中文基本上就是杂音，看起来是convertor的问题，需要重新训练。

**Comment by DvHuang** [comment]
因为合成模型默认16k，输出的mel特征是16k

**Comment by HaSaKiYasuooo** [comment]
> 这个文件应该还伴随一个config文件，要一起下载

我也放置了config文件出现报错

**Comment by HaSaKiYasuooo** [comment]
找到了
![image](https://github.com/babysor/MockingBird/assets/87591236/a90abbad-7c55-4ffd-b0c1-d1e647220893)
源码明确需要文件名称为hifigan字符串相关，
