### ISSUE TITLE
开启图形化界面时报错

### ISSUE THREAD

**Issue by wmxuan666** [babysor/MockingBird#528]
D:\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "D:\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "D:\MockingBird-main\toolbox\ui.py", line 1, in <module>
    from PyQt5.QtCore import Qt, QStringListModel
ModuleNotFoundError: No module named 'PyQt5'

**Comment by babysor** [comment]
现在的图形化界面正在废弃中，你可以先后运行 `git fetch` , `git switch dev`进行更新代码后运行 `python web.py `

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
Install PyQt5 using either pip or apt search on the web your self.
