### ISSUE TITLE
点击 record 之后 会报  Axis limits canot be  NaN or Inf

### ISSUE THREAD

**Issue by newluhuibiao** [babysor/MockingBird#547]
<img width="377" alt="捕获" src="https://user-images.githubusercontent.com/12454131/167635402-92c187f6-741f-4096-9e95-6d27b7e52f6e.PNG">

**Comment by newluhuibiao** [comment]
Building hifigan
Loading 'vocoder\saved_models\pretrained\g_hifigan.pt'
Complete.
Removing weight norm...
Traceback (most recent call last):
  File "D:\AI\MockingBird-0.0.1\toolbox\__init__.py", line 123, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "D:\AI\MockingBird-0.0.1\toolbox\__init__.py", line 331, in vocode
    self.ui.draw_embed(embed, name, "generated")
  File "D:\AI\MockingBird-0.0.1\toolbox\ui.py", line 70, in draw_embed
    embed_ax.figure.canvas.draw()
  File "C:\Python39\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "C:\Python39\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "C:\Python39\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "C:\Python39\lib\site-packages\matplotlib\figure.py", line 2823, in draw
    artists = self._get_draw_artists(renderer)
  File "C:\Python39\lib\site-packages\matplotlib\figure.py", line 238, in _get_draw_artists
    ax.apply_aspect()
  File "C:\Python39\lib\site-packages\matplotlib\axes\_base.py", line 1972, in apply_aspect
    self.set_xbound(x_trf.inverted().transform([x0, x1]))
  File "C:\Python39\lib\site-packages\matplotlib\axes\_base.py", line 3573, in set_xbound
    self.set_xlim(sorted((lower, upper),
  File "C:\Python39\lib\site-packages\matplotlib\axes\_base.py", line 3697, in set_xlim
    left = self._validate_converted_limits(left, self.convert_xunits)
  File "C:\Python39\lib\site-packages\matplotlib\axes\_base.py", line 3614, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf

**Comment by babysor** [comment]
窗口太小，用鼠标拉大一点

**Comment by nmgxx** [comment]
同问这个问题怎么解决？

**Comment by babysor** [comment]
用鼠标拉大一下窗口就可以了
