### ISSUE TITLE
最后一步时显示“不是有效的 Win32 应用程序”，大佬们求救！！

### ISSUE THREAD

**Issue by BuyDew** [babysor/MockingBird#567]
`E:\Program\MockingBird-main\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "E:\Program\MockingBird-main\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "E:\Program\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "E:\Program\MockingBird-main\MockingBird-main\toolbox\ui.py", line 7, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "E:\Program\MockingBird-main\MockingBird-main\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "E:\Program\MockingBird-main\MockingBird-main\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 126, in <module>
    raise err
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\lib\cufft64_10.dll" or one of its dependencies.

E:\Program\MockingBird-main\MockingBird-main>python demo_toolbox.py
Traceback (most recent call last):
  File "E:\Program\MockingBird-main\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "E:\Program\MockingBird-main\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "E:\Program\MockingBird-main\MockingBird-main\toolbox\ui.py", line 7, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "E:\Program\MockingBird-main\MockingBird-main\encoder\inference.py", line 2, in <module>
    from encoder.model import SpeakerEncoder
  File "E:\Program\MockingBird-main\MockingBird-main\encoder\model.py", line 5, in <module>
    from torch.nn.utils import clip_grad_norm_
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\__init__.py", line 126, in <module>
    raise err
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。 Error loading "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\lib\cufft64_10.dll" or one of its dependencies.`

最后一步时出现这种情况，大佬们求解决！

**Comment by BuyDew** [comment]
Install last step shows "Not a valid Win32 application", please help! That‘s the code.

**Comment by LeChaPatteImpitoyable** [comment]
me too

**Comment by LeChaPatteImpitoyable** [comment]
![image](https://user-images.githubusercontent.com/29195366/190589607-39f3c69b-441a-4e63-948b-c6ccddcd95ef.png)
