### ISSUE TITLE
请教训练vocoder报错问题

### ISSUE THREAD

**Issue by 1239hy** [babysor/MockingBird#580]
错误
![QQ图片20220525234139](https://user-images.githubusercontent.com/102406483/170305487-a01305cd-cd8e-4640-9b60-ad2ed4e1d83b.gif)
请教这是什么错误，如何处理

**Comment by JXTang-syc** [comment]
下载最新版代码试试

**Comment by 1239hy** [comment]
> 下载最新版代码试试

> 下载最新版代码试试

大佬，最新代码在哪里？

**Comment by JXTang-syc** [comment]
> > 下载最新版代码试试
> 
> > 下载最新版代码试试
> 
> 大佬，最新代码在哪里？

第一，我不是大佬，我只是小白
第二，就是code里面的download as zip
#577 可以参考一下

**Comment by 1239hy** [comment]
> > > 下载最新版代码试试
> > 
> > 
> > > 下载最新版代码试试
> > 
> > 
> > 大佬，最新代码在哪里？
> 
> 第一，我不是大佬，我只是小白 第二，就是code里面的download as zip #577 可以参考一下

是下一次新的项目文件，还是不行呢

Microsoft Windows [版本 10.0.19044.1706]
(c) Microsoft Corporation。保留所有权利。

D:\shengyin\MockingBird-main>python vocoder_train.py aftest D:\shengyin\wj10 hifigan
  File "D:\shengyin\MockingBird-main\vocoder_train.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

D:\shengyin\MockingBird-main>python vocoder_train.py aftest D:\shengyin\wj10 hifigan
Traceback (most recent call last):
  File "D:\shengyin\MockingBird-main\vocoder_train.py", line 4, in <module>
    from vocoder.fregan.train import train as train_fregan
  File "D:\shengyin\MockingBird-main\vocoder\fregan\train.py", line 15, in <module>
    from vocoder.fregan.discriminator import ResWiseMultiPeriodDiscriminator, ResWiseMultiScaleDiscriminator
  File "D:\shengyin\MockingBird-main\vocoder\fregan\discriminator.py", line 8, in <module>
    from vocoder.fregan.dwt import DWT_1D
  File "D:\shengyin\MockingBird-main\vocoder\fregan\dwt.py", line 10, in <module>
    import pywt
ModuleNotFoundError: No module named 'pywt'

D:\shengyin\MockingBird-main>

**Comment by 1239hy** [comment]
> > > 下载最新版代码试试
> > 
> > 
> > > 下载最新版代码试试
> > 
> > 
> > 大佬，最新代码在哪里？
> 
> 第一，我不是大佬，我只是小白 第二，就是code里面的download as zip #577 可以参考一下

麻烦可以截图一下，下载位置吗？感谢

**Comment by 1239hy** [comment]
> > > 下载最新版代码试试
> > 
> > 
> > > 下载最新版代码试试
> > 
> > 
> > 大佬，最新代码在哪里？
> 
> 第一，我不是大佬，我只是小白 第二，就是code里面的download as zip #577 可以参考一下

貌似代码还没有更新

**Comment by JXTang-syc** [comment]
这个
您试试再来一次pip install -r requirements.txt

**Comment by 1239hy** [comment]
> pip install -r requirements.txt

结果报错了

ERROR: Could not build wheels for pyworld which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.4; however, version 22.1.1 is available.
You should consider upgrading via the 'C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

**Comment by JXTang-syc** [comment]
那试试先C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip更新pip
不应该报错

**Comment by 1239hy** [comment]
> 那试试先C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip更新pip 不应该报错

还是一样的报错呢，万分感谢。。还有没有其他的可能

**Comment by HaSaKiYasuooo** [comment]
> > 那试试先C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip更新pip 不应该报错
> 
> 还是一样的报错呢，万分感谢。。还有没有其他的可能

https://blog.csdn.net/welcome_yu/article/details/115163012
