### ISSUE TITLE
web端只能在windows下面用吗？

### ISSUE THREAD

**Issue by jingzhuer** [babysor/MockingBird#584]
File "/home/wiseatc/zzc/hugface/lib/python3.7/site-packages/streamlit/scriptrunner/script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
  File "/tmp/tmpm_oj5169.py", line 14, in <module>
    render_streamlit_ui()
  File "/home/wiseatc/MockingBird/mkgui/base/ui/streamlit_ui.py", line 838, in render_streamlit_ui
    opyrator = getOpyrator(mode)
  File "/home/wiseatc/MockingBird/mkgui/base/ui/streamlit_ui.py", line 818, in getOpyrator
    from mkgui.app import synthesize
  File "/home/wiseatc/MockingBird/mkgui/app.py", line 1, in <module>
    from asyncio.windows_events import NULL
  File "/usr/local/lib/python3.7/asyncio/windows_events.py", line 3, in <module>
    import _overlapped
ModuleNotFoundError: No module named '_overlapped'

**Comment by babysor** [comment]
请问是什么系统？

**Comment by jingzhuer** [comment]
ubuntu16

**Comment by Yanyouke** [comment]
我的是Mac M1，好像我们的web.py只能在win下面使用

**Comment by babysor** [comment]
> 我的是Mac M1，好像我们的web.py只能在win下面使用

mac也是这个错误吗？确实这个没在多系统下测试验证过，我晚点试试

**Comment by clstech** [comment]
我的是Mac M1 ,启动后报错
`2022-06-10 17:34:47.155 Traceback (most recent call last):
  File "/Users/chenchun/opt/anaconda3/lib/python3.9/site-packages/streamlit/scriptrunner/script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
  File "/var/folders/01/b8hkkgsj4x9bxstz0v77kq840000gn/T/tmpxhpq66zj.py", line 14, in <module>
    render_streamlit_ui()
  File "/Users/chenchun/CloneProjects/MockingBird/mkgui/base/ui/streamlit_ui.py", line 838, in render_streamlit_ui
    opyrator = getOpyrator(mode)
  File "/Users/chenchun/CloneProjects/MockingBird/mkgui/base/ui/streamlit_ui.py", line 818, in getOpyrator
    from mkgui.app import synthesize
  File "/Users/chenchun/CloneProjects/MockingBird/mkgui/app.py", line 1, in <module>
    from asyncio.windows_events import NULL
  File "/Users/chenchun/opt/anaconda3/lib/python3.9/asyncio/windows_events.py", line 6, in <module>
    raise ImportError('win32 only')
ImportError: win32 only`

**Comment by markjun** [comment]
![image](https://user-images.githubusercontent.com/12456223/175276204-eeafe1b6-2718-48a0-b23f-e72b13033dad.png)

**Comment by babysor** [comment]
感谢反馈错误，我今天修复一下。
