### ISSUE TITLE
训练synthesizer出现错误

### ISSUE THREAD

**Issue by Chopin68** [babysor/MockingBird#599]
Loading weights at synthesizer\saved_models\jia\jia.pt
Tacotron weights loaded from step 0
Using inputs from:
        Z:\制作数据集\1\SV2TTS\synthesizer\train.txt
        Z:\制作数据集\1\SV2TTS\synthesizer\mels
        Z:\制作数据集\1\SV2TTS\synthesizer\embeds
Found 120 samples
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|   10k Steps    |     12     |     0.001     |        2         |
+----------------+------------+---------------+------------------+

Traceback (most recent call last):
  File "Z:\deeplearing_project\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "Z:\deeplearing_project\MockingBird-main\synthesizer\train.py", line 199, in train
    m1_hat, m2_hat, attention, stop_pred = model(texts, mels, embeds)
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Z:\deeplearing_project\MockingBird-main\synthesizer\models\tacotron.py", line 406, in forward
    style_embed = self.gst(speaker_embedding, speaker_embedding) # for training, speaker embedding can represent both style inputs and referenced
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Z:\deeplearing_project\MockingBird-main\synthesizer\models\global_style_token.py", line 26, in forward
    style_embed = self.stl(enc_out)
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Z:\deeplearing_project\MockingBird-main\synthesizer\models\global_style_token.py", line 101, in forward
    style_embed = self.attention(query, keys)
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Z:\deeplearing_project\MockingBird-main\synthesizer\models\global_style_token.py", line 127, in forward
    querys = self.W_query(query)  # [N, T_q, num_units]
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\CHOPY\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (12x512 and 768x512)

没见过的错误 ！！

**Comment by HSQhere** [comment]
建议重下一个项目，可能是代码缺失

**Comment by HSQhere** [comment]
也可以尝试改batch size值

**Comment by Chopin68** [comment]
> 建议重下一个项目，可能是代码

是的重下就好了，但是确实第一次见这个错误

**Comment by babysor** [comment]
第一次看到这个错误，你有换python版本吗？
