### ISSUE TITLE
运行python demo_toolbox.py 出现UnicodeDecodeError错误

### ISSUE THREAD

**Issue by jiugexuan** [babysor/MockingBird#615]
**Summary[问题简述（一句话）]**

运行python demo_toolbox.py 出现UnicodeDecodeError错误

**Env & To Reproduce[复现与环境]**

在成功出现工具界面后闪退。
使用的python 是anaconda python 3.9
编译工具是visual studio code
平台是笔记本电脑

控制台输出如下：

PS D:\#_MockingBird-main> python demo_toolbox.py
Arguments:
    datasets_root:          None
    vc_mode:                False
    enc_models_dir:         encoder\saved_models
    syn_models_dir:         synthesizer\saved_models
    voc_models_dir:         vocoder\saved_models
    extractor_models_dir:   ppg_extractor\saved_models
    convertor_models_dir:   ppg2mel\saved_models
    cpu:                    False
    seed:                   None
    no_mp3_support:         False

Warning: you did not pass a root directory for datasets as argument.
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
        aidatatang_200zh/corpus/dev
        aidatatang_200zh/corpus/test
        aishell3/test/wav
        magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "D:\#_MockingBird-main\demo_toolbox.py", line 49, in <module>
    Toolbox(**vars(args))
  File "D:\#_MockingBird-main\toolbox\__init__.py", line 81, in __init__
    self.setup_events()
  File "D:\#_MockingBird-main\toolbox\__init__.py", line 127, in setup_events
    self.ui.setup_audio_devices(Synthesizer.sample_rate)
  File "D:\#_MockingBird-main\toolbox\ui.py", line 149, in setup_audio_devices
    for device in sd.query_devices():
  File "C:\Users\jiuge\.conda\envs\MockingBird\lib\site-packages\sounddevice.py", line 559, in query_devices
    return DeviceList(query_devices(i)
  File "C:\Users\jiuge\.conda\envs\MockingBird\lib\site-packages\sounddevice.py", line 559, in <genexpr>
    return DeviceList(query_devices(i)
  File "C:\Users\jiuge\.conda\envs\MockingBird\lib\site-packages\sounddevice.py", line 573, in query_devices
    name = name_bytes.decode('utf-8')
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte**

**Comment by jiugexuan** [comment]
发现是由 sd.query_devices() 这个函数引发的UnicodeDecodeError
