### ISSUE TITLE
python web.py运行报错，求解~~~

### ISSUE THREAD

**Issue by 11-Years** [babysor/MockingBird#618]
环境
操作系统：window10
Anaconda版本：4.3
Python版本：3.7

运行：python demo_toolbox.py -d .\samples （可以正常运行）
运行：python web.py报错，错误信息如下：
(pythone37) E:\CACHE_DATA\CHROME\MockingBird-main-new\MockingBird-main>python web.py

  You can now view your Streamlit app in your browser.

  Network URL: http://172.20.10.3:8080
  External URL: http://58.246.155.96:8080

Loaded synthesizer models: 2
Loaded encoders models: 2
Loaded vocoders models: 2
2022-06-16 19:48:10.184 Traceback (most recent call last):
  File "E:\THIRD_PARTY\Anaconda3\envs\pythone37\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\CHARLES\AppData\Local\Temp\tmp0t72pr3r.py", line 14, in <module>
    render_streamlit_ui()
  File "E:\CACHE_DATA\CHROME\MockingBird-main-new\MockingBird-main\mkgui\base\ui\streamlit_ui.py", line 838, in render_streamlit_ui
    opyrator = getOpyrator(mode)
  File "E:\CACHE_DATA\CHROME\MockingBird-main-new\MockingBird-main\mkgui\base\ui\streamlit_ui.py", line 818, in getOpyrator
    from mkgui.app import synthesize
  File "E:\CACHE_DATA\CHROME\MockingBird-main-new\MockingBird-main\mkgui\app.py", line 75, in <module>
    class Output(BaseModel):
  File "E:\CACHE_DATA\CHROME\MockingBird-main-new\MockingBird-main\mkgui\app.py", line 76, in Output
    __root__: tuple[AudioEntity, AudioEntity]
TypeError: 'type' object is not subscriptable

**Comment by babysor** [comment]
已经推了修复
