### ISSUE TITLE
运行pre.py时出错，是虚拟内存的问题么？

### ISSUE THREAD

**Issue by mx2846** [babysor/MockingBird#626]
运行pre.py时 报错，
F:\mockingbird\MockingBird-main\MockingBird-main>python pre.py H:/data -d aidatatang_200zh -n 4
Using data from:
    H:\data\aidatatang_200zh\corpus\train
aidatatang_200zh:   0%|                                                    | 0/1 [00:00<?, ?speakers/s]F:\mockingbird\MockingBird-main\MockingBird-main\synthesizer\preprocess_speaker.py:66: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  wav, _ = librosa.load(wav_fpath, hparams.sample_rate)
F:\mockingbird\MockingBird-main\MockingBird-main\synthesizer\audio.py:170: FutureWarning: Pass sr=16000, n_fft=800 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  return librosa.filters.mel(hparams.sample_rate, hparams.n_fft, n_mels=hparams.num_mels,
F:\mockingbird\MockingBird-main\MockingBird-main\synthesizer\preprocess_speaker.py:66: FutureWarning: Pass sr=16000 as keyword args. From version 0.10 passing these as positional arguments will result in an error
  wav, _ = librosa.load(wav_fpath, hparams.sample_rate)
aidatatang_200zh:   0%|                                                    | 0/1 [00:43<?, ?speakers/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "F:\mockingbird\MockingBird-main\MockingBird-main\synthesizer\preprocess_speaker.py", line 97, in preprocess_speaker_general
    metadata.append(_process_utterance(wav, text, out_dir, sub_basename,
  File "F:\mockingbird\MockingBird-main\MockingBird-main\synthesizer\preprocess_speaker.py", line 42, in _process_utterance
    wav = encoder.preprocess_wav(wav, normalize=False, trim_silence=True)
  File "F:\mockingbird\MockingBird-main\MockingBird-main\encoder\audio.py", line 48, in preprocess_wav
    wav = trim_long_silences(wav)
  File "F:\mockingbird\MockingBird-main\MockingBird-main\encoder\audio.py", line 83, in trim_long_silences
    pcm_wave = struct.pack("%dh" % len(wav), *(np.round(wav * int16_max)).astype(np.int16))
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\mockingbird\MockingBird-main\MockingBird-main\pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "F:\mockingbird\MockingBird-main\MockingBird-main\synthesizer\preprocess.py", line 74, in preprocess_dataset
    for speaker_metadata in tqdm(job, dataset, len(speaker_dirs), unit="speakers"):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 870, in next
    raise value
MemoryError

**Comment by mimi0123** [comment]
我跟你一样的错误 解决了吗

**Comment by babysor** [comment]
按readme处理虚拟内存
