### ISSUE TITLE
Wiki 需要补全

### ISSUE THREAD

**Issue by Limingrui0** [babysor/MockingBird#656]
**Summary[问题简述（一句话）]**
Wiki的补全十分需要，在 `快速开始` 这一栏里应该有版本描述。因为 torch 的版本有不同。

建议部分改为

```markdown
拉取本代码库 tag 0.0.1
安装pytorch 1.9.0 torchvision 0.10.0 cuda 11.1 或 cuda10.2 或 Onlycpu
```

本pytorch安装部分在readme及Wiki部分都没有描述清楚。同 issue #655

**Comment by Limingrui0** [comment]
因为我只有在这个版本下运行成功，欢迎大佬来指导

**Comment by babysor** [comment]
这里有遇到什么依赖冲突嘛？我可以都更新一下到最新或者最兼容的版本

**Comment by Limingrui0** [comment]
@babysor 这是以OnlyCPU版本的方式安装最新版 Pytorch （以解决CUDA版本的冲突）安装最新版reuire的截图。其中 VC++ 为最新版本，GCC 执行 make 没有问题。
```bash
cd G:\Mock
git init
git pull https://github.com/babysor/MockingBird.git
conda create -n Mock python=3.9
conda activate Mock
conda install pytorch torchvision torchaudio cpuonly -c pytorch
pip install -r requirements.txt
pip install webrtcvad-wheels
```
附安装完reque为 [查看](https://gist.futils.com/?aff602212f659424#96hVe8uRdktmWdWSqgchRuZpcxhp5ETFmCME1afZjEmK)

以上是执行的命令，紧接执行 `python web.py` 为

```bash
Traceback (most recent call last):
  File "C:\Users\Work\OneDrive - waterdropadmin\桌面\MockingBird-main\web.py", line 3, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
```

执行 `python demo_toolbox.py` 为
```bash
#等待一段时间
Traceback (most recent call last):
  File "C:\Users\Work\OneDrive - waterdropadmin\桌面\MockingBird-main\demo_toolbox.py", line 2, in <module>
    from toolbox import Toolbox
  File "C:\Users\Work\OneDrive - waterdropadmin\桌面\MockingBird-main\toolbox\__init__.py", line 1, in <module>
    from toolbox.ui import UI
  File "C:\Users\Work\OneDrive - waterdropadmin\桌面\MockingBird-main\toolbox\ui.py", line 7, in <module>
    from encoder.inference import plot_embedding_as_heatmap
  File "C:\Users\Work\OneDrive - waterdropadmin\桌面\MockingBird-main\encoder\inference.py", line 3, in <module>
    from encoder.audio import preprocess_wav   # We want to expose this function from here
  File "C:\Users\Work\OneDrive - waterdropadmin\桌面\MockingBird-main\encoder\audio.py", line 7, in <module>
    import librosa
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\librosa\util\__init__.py", line 84, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\librosa\util\files.py", line 28, in <module>
    __data_path = os.environ.get("LIBROSA_DATA_DIR", pooch.os_cache("librosa"))
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\pooch\utils.py", line 99, in os_cache
    return Path(appdirs.user_cache_dir(project))
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\Users\Work\miniconda3\envs\Mock\lib\site-packages\appdirs.py", line 480, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed while importing shell: 找不到指定的程序。
```

而在` tag0.0.1` 就完全没问题，只需要将 torch 改为 1.19 vision 0.10.0

附 [环境](https://gist.futils.com/?4120aa4050ce9d9a#HbP7pY6dX9LPqzm19mQsT7H4cnAnMqLMWrALPRcCDZwY)

**Comment by Limingrui0** [comment]
如果可以的话，您把您的环境帖一下

**Comment by babysor** [comment]
我感觉你是python3.9的问题，我晚点试一下
