### ISSUE TITLE
奇奇怪怪的报错

### ISSUE THREAD

**Issue by Secretboy-SMR** [babysor/MockingBird#680]
Using model: Tacotron
Using device: cuda

Initialising Tacotron Model...

\Loading the json with %s
 {'sample_rate': 16000, 'n_fft': 800, 'num_mels': 80, 'hop_size': 200, 'win_size': 800, 'fmin': 55, 'min_level_db': -100, 'ref_level_db': 20, 'max_abs_value': 4.0, 'preemphasis': 0.97, 'preemphasize': True, 'tts_embed_dims': 512, 'tts_encoder_dims': 256, 'tts_decoder_dims': 128, 'tts_postnet_dims': 512, 'tts_encoder_K': 5, 'tts_lstm_dims': 1024, 'tts_postnet_K': 5, 'tts_num_highways': 4, 'tts_dropout': 0.5, 'tts_cleaner_names': ['basic_cleaners'], 'tts_stop_threshold': -3.4, 'tts_schedule': [[2, 0.001, 10000, 12], [2, 0.0005, 15000, 12], [2, 0.0002, 20000, 12], [2, 0.0001, 30000, 12], [2, 5e-05, 40000, 12], [2, 1e-05, 60000, 12], [2, 5e-06, 160000, 12], [2, 3e-06, 320000, 12], [2, 1e-06, 640000, 12]], 'tts_clip_grad_norm': 1.0, 'tts_eval_interval': 500, 'tts_eval_num_samples': 1, 'tts_finetune_layers': [], 'max_mel_frames': 900, 'rescale': True, 'rescaling_max': 0.9, 'synthesis_batch_size': 16, 'signal_normalization': True, 'power': 1.5, 'griffin_lim_iters': 60, 'fmax': 7600, 'allow_clipping_in_normalization': True, 'clip_mels_length': True, 'use_lws': False, 'symmetric_mels': True, 'trim_silence': True, 'speaker_embedding_size': 256, 'silence_min_duration_split': 0.4, 'utterance_min_duration': 1.6, 'use_gst': True, 'use_ser_for_gst': True}
Trainable Parameters: 0.000M

Loading weights at synthesizer\saved_models\xb\xb.pt
Tacotron weights loaded from step 144
Using inputs from:
        C:\Users\hyhhy\Desktop\AIless\vc\SV2TTS\synthesizer\train.txt
        C:\Users\hyhhy\Desktop\AIless\vc\SV2TTS\synthesizer\mels
        C:\Users\hyhhy\Desktop\AIless\vc\SV2TTS\synthesizer\embeds
Found 284 samples
+----------------+------------+---------------+------------------+
| Steps with r=2 | Batch Size | Learning Rate | Outputs/Step (r) |
+----------------+------------+---------------+------------------+
|    9k Steps    |     12     |     0.001     |        2         |
+----------------+------------+---------------+------------------+

Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127
Traceback (most recent call last):
  File "C:\Users\hyhhy\Desktop\AIless\MockingBird\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "C:\Users\hyhhy\Desktop\AIless\MockingBird\synthesizer\train.py", line 215, in train
    optimizer.step()
  File "C:\Users\hyhhy\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\hyhhy\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\hyhhy\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 157, in step
    adam(params_with_grad,
  File "C:\Users\hyhhy\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 213, in adam
    func(params,
  File "C:\Users\hyhhy\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

**Comment by Noct-Cp** [comment]
我是回到torch 1.11.0解决的，参考#631

**Comment by b95595** [comment]
用新的安装包就行
