### ISSUE TITLE
合成器训练停止后，如何用于其他的训练

### ISSUE THREAD

**Issue by sixtolink** [babysor/MockingBird#700]
之前都是使用作者或者别人打包好的训练集继续训练，但我用自己训练的数据集训练后，继续训练会出现抱错。请问是什么原因。报错如下：
Traceback (most recent call last):
  File "D:\mockingbird2\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "D:\mockingbird2\MockingBird-main\synthesizer\train.py", line 215, in train
    optimizer.step()
  File "C:\Program Files\Python39\lib\site-packages\torch\optim\optimizer.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\torch\optim\adam.py", line 157, in step
    adam(params_with_grad,
  File "C:\Program Files\Python39\lib\site-packages\torch\optim\adam.py", line 213, in adam
    func(params,
  File "C:\Program Files\Python39\lib\site-packages\torch\optim\adam.py", line 255, in _single_tensor_adam
    assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
AssertionError: If capturable=False, state_steps should not be CUDA tensors.

**Comment by babysor** [comment]
pytorch版本不匹配导致的
