### ISSUE TITLE
导入他人模型出错

### ISSUE THREAD

**Issue by alpha764** [babysor/MockingBird#703]
错误:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MockingBird-0.0.1\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "C:\Users\Administrator\Desktop\MockingBird-0.0.1\synthesizer\train.py", line 114, in train
    model.load(weights_fpath, optimizer)
  File "C:\Users\Administrator\Desktop\MockingBird-0.0.1\synthesizer\models\tacotron.py", line 526, in load
    optimizer.load_state_dict(checkpoint["optimizer_state"])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\optimizer.py", line 171, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

导入他人模型都不行,只有自己的可以用

**Comment by alpha764** [comment]
使用https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ#list/path=%2Fsharelink2097319157-798950240644030%2FRealtime-Voice-Clone-Chinese%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%2Fsynthesizer%2Fsaved_models%2Fmandarin&parentPath=%2Fsharelink2097319157-798950240644030
的ceshi.pt

**Comment by alpha764** [comment]
已经解决了删不掉只能留住了

**Comment by alpha764** [comment]
已经解决了

**Comment by babysor** [comment]
代码版本和模型没对上

**Comment by gwegwegewtg** [comment]
> 代码版本和模型没对上

所以具体应该如何解决这个问题呢

**Comment by ODomWang** [comment]
解决了吗 老哥 我也是这个问题，搜了一圈都是说模型版本的问题 我把作者嘴贱的几个模型都试了 还是不行

**Comment by alpha764** [comment]
> 解决了吗 老哥 我也是这个问题，搜了一圈都是说模型版本的问题 我把作者嘴贱的几个模型都试了 还是不行

大概了解啥意思了，就是mockingbird有很多的版本，假如你一个模型一直不能用的话必须要下载其他版本的mockingbird才能用

**Comment by stu00608** [comment]
我也是一樣的問題，在v0.0.1使用FawenYo的模型繼續訓練時報錯，想知道能跑起來的都切到哪一個commit

**Comment by stu00608** [comment]
> 我也是一樣的問題，在v0.0.1使用FawenYo的模型繼續訓練時報錯，想知道能跑起來的都切到哪一個commit

我發現使用該模型作者的Fork改掉symbol的問題之後可以順利跑起來，供大家參考：https://github.com/FawenYo/MockingBird

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/40068587/210293384-7fce5b58-bfc8-4fb4-a69a-44fa3b27166e.png">
