### ISSUE TITLE
分享王冰冰数据集，希望大佬用这个数据集训练的模型也能分享出来

### ISSUE THREAD

**Issue by Uranus-sun** [babysor/MockingBird#721]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.

**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型

**Screenshots[截图（如有）]**
If applicable, add screenshots to help

**Comment by mochaYJ12138** [comment]
大佬 文件已过期 能重新分享一下么

**Comment by dtx525942103** [comment]
> 链接：https://pan.baidu.com/s/1ScihCTR90Bnf_xdanqPyLg 提取码：77nv 希望大佬们用这个数据集训练的模型也能分享出来

你能在分享一下嘛？我能做出来

**Comment by Uranus-sun** [comment]
数据集链接：https://pan.baidu.com/s/190jnZS6egANYUppDISecaA 提取码：bjkc
训练好的模型链接：链接：https://pan.baidu.com/s/1cn51AyWNivGXaQa-vJ8-4A 提取码：tj2r

**Comment by mochaYJ12138** [comment]
> 数据集链接：https://pan.baidu.com/s/190jnZS6egANYUppDISecaA 提取码：bjkc 训练好的模型链接：链接：https://pan.baidu.com/s/1cn51AyWNivGXaQa-vJ8-4A 提取码：tj2r
感谢 大佬

**Comment by dsyrock** [comment]
请问这个数据集是按照哪个数据集的格式来做的？

**Comment by justforyourdream** [comment]
aidatatang_200zh: 100%|██████████| 66/66 [00:02<00:00, 26.00speakers/s]
The dataset consists of 0 utterances, 0 mel frames, 0 audio timesteps (0.00 hours).
Traceback (most recent call last):
  File "F:/newpycharmproject/pythonProject/mockingbirdchina/pre.py", line 74, in <module>
    preprocess_dataset(**vars(args))
  File "F:\newpycharmproject\pythonProject\mockingbirdchina\synthesizer\preprocess.py", line 88, in preprocess_dataset
    print("Max input length (text chars): %d" % max(len(m[5]) for m in metadata))
ValueError: max() arg is an empty sequence

**Comment by justforyourdream** [comment]
请问训练的是哪个，文件路径格式。
