### ISSUE TITLE
loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by hyhzl** [babysor/MockingBird#739]
**Summary[问题简述（一句话）]**
 using version v0.0.1,and pretrained model https://pan.baidu.com/s/1PI-hM3sn5wbeChRryX-RCQ 提取码：2021,but occur issue:
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by babysor** [comment]
Thanks for atting me here. I prefer to discuss here since we can focus on the issue itself. It looks that you are not using the right pretrained file for your model. pls attach more info

**Comment by hyhzl** [comment]
appreciate for your answer.
encouter another issue when trying Synthesizing wav locally,by executing demo_cli.py,but having problem at final step:
Caught exception: ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()')
it seems the problem of ' generated_wav = encoder.preprocess_wav(generated_wav) '  this sentence, 206 line of demo_cli.py
@babysor

**Comment by hyhzl** [comment]
Loading weights at synthesizer/saved_models/mandarin/mandarin.pt
Traceback (most recent call last):
  File "synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "/jfs-cache/ai-prj/MockingBird/synthesizer/train.py", line 114, in train
    model.load(weights_fpath, optimizer)
  File "/jfs-cache/ai-prj/MockingBird/synthesizer/models/tacotron.py", line 527, in load
    optimizer.load_state_dict(checkpoint["optimizer_state"])
  File "/jfs-cache/ai-prj/conda_env/mb/lib/python3.8/site-packages/torch/optim/optimizer.py", line 201, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by hyhzl** [comment]
@babysor
