### ISSUE TITLE
使用Sound_File_Processing-master软件音频切割 在执行pyhton long_file_cut_by_srt.py命令出现以下问题 希望大佬帮助看一下

### ISSUE THREAD

**Issue by mochaYJ12138** [babysor/MockingBird#749]
D:\video-srt-gui-ffm\Sound_File_Processing-master>pip install -r requirements.txt
Requirement already satisfied: pydub==0.25.1 in d:\python\lib\site-packages (from -r requirements.txt (line 1)) (0.25.1)

D:\video-srt-gui-ffm\Sound_File_Processing-master>python long_file_cut_by_srt.py
srt/loy2.srt
wav/input/loy2.wav
wav/input/loy2.mp3
Traceback (most recent call last):
  File "D:\video-srt-gui-ffm\Sound_File_Processing-master\long_file_cut_by_srt.py", line 77, in <module>
    cut_file_by_srt(sound_root_path, srt_dict)
  File "D:\video-srt-gui-ffm\Sound_File_Processing-master\long_file_cut_by_srt.py", line 48, in cut_file_by_srt
    sound_cut = sound[start_time:end_time + 50]  # 网易的裁切太激进了，所以加50毫秒
**UnboundLocalError: local variable 'sound' referenced before assignment**

**Comment by mochaYJ12138** [comment]
解决了 音频没有转换成 wav 直接修改的后缀名 导致音频有问题
