### ISSUE TITLE
替换了别人的模型继续训练后发现报错，这是哪里出现问题了吗？有大佬可以帮忙解读一下吗？谢谢了

### ISSUE THREAD

**Issue by 2223101** [babysor/MockingBird#756]
Loading weights at synthesizer\saved_models\chara\chara.pt
Traceback (most recent call last):
  File "I:\voice\audio\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "I:\voice\audio\MockingBird-main\synthesizer\train.py", line 121, in train
    model.load(weights_fpath, device, optimizer)
  File "I:\voice\audio\MockingBird-main\synthesizer\models\base.py", line 51, in load
    self.load_state_dict(checkpoint["model_state"], strict=False)
  File "C:\Users\胡一潇\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Tacotron:
        size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([149, 512]) from checkpoint, the shape in current model is torch.Size([169, 512]).

**Comment by 2223101** [comment]
> 代码版本没对上

那有啥解决办法吗大佬
