### ISSUE TITLE
按照视频的方法换了作者的数据集之后，再运行报错

### ISSUE THREAD

**Issue by VictorSlave** [babysor/MockingBird#772]
错误信息如下：
E:\aiSound\MockingBird\MockingBird-main\synthesizer\synthesizer_dataset.py:84: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:204.)
  embeds = torch.tensor(embeds)
E:\aiSound\MockingBird\MockingBird-main\synthesizer\synthesizer_dataset.py:84: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:204.)
  embeds = torch.tensor(embeds)
C:\Users\86186\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\functional.py:1949: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "E:\aiSound\MockingBird\MockingBird-main\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "E:\aiSound\MockingBird\MockingBird-main\synthesizer\train.py", line 208, in train
    optimizer.step()
  File "C:\Users\86186\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\86186\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\86186\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 157, in step
    adam(params_with_grad,
  File "C:\Users\86186\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 213, in adam
    func(params,
  File "C:\Users\86186\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\optim\adam.py", line 262, in _single_tensor_adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (1024) must match the size of tensor b (3) at non-singleton dimension 3

**Comment by zhuhero2012** [comment]
同问

**Comment by zhangmm2** [comment]
同问
