### ISSUE TITLE
PPG训练时的报错，请帮忙看看

### ISSUE THREAD

**Issue by benny1227** [babysor/MockingBird#794]
PPG预处理很顺利，ppg2mel.yaml路径也改了，但是这个错误提示怎么都解决不了，请大家帮忙看看能否有经验分享下。

D:\MockingBird-main>python ppg2mel_train.py --config .\ppg2mel\saved_models\ppg2mel.yaml --oneshotvc
Traceback (most recent call last):
  File "D:\MockingBird-main\ppg2mel_train.py", line 67, in <module>
    main()
  File "D:\MockingBird-main\ppg2mel_train.py", line 50, in main
    config = HpsYaml(paras.config)
  File "D:\MockingBird-main\utils\load_yaml.py", line 44, in __init__
    hps = load_hparams(yaml_file)
  File "D:\MockingBird-main\utils\load_yaml.py", line 8, in load_hparams
    for doc in docs:
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\__init__.py", line 127, in load_all
    loader = Loader(stream)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\benny\AppData\Local\Programs\Python\Python39\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
UnicodeDecodeError: 'gbk' codec can't decode byte 0x86 in position 176: illegal multibyte sequence

**Comment by babysor** [comment]
贴一下你的yml，看起来格式没搞对
