### ISSUE TITLE
合成失败

### ISSUE THREAD

**Issue by ajunbudou** [babysor/MockingBird#80]
你好 我使用sishell3数据集来进行合成 ，使用的是你提供的预训练模型出现如下错误。请问如何修改呢‘？
Traceback (most recent call last):
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'build_te'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 1095, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 1037, in frombuf
    chksum = nti(buf[148:156])
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 189, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\tj\anaconda\envs\gpu2\lib\site-packages\torch\serialization.py", line 555, in _load
    return legacy_load(f)
  File "G:\tj\anaconda\envs\gpu2\lib\site-packages\torch\serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "G:\tj\anaconda\envs\gpu2\lib\tarfile.py", line 2301, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\voice cloning\MockingBird-main-version2\toolbox\__init__.py", line 129, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "G:\voice cloning\MockingBird-main-version2\toolbox\__init__.py", line 243, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "G:\voice cloning\MockingBird-main-version2\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "G:\voice cloning\MockingBird-main-version2\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "G:\voice cloning\MockingBird-main-version2\synthesizer\models\tacotron.py", line 496, in load
    checkpoint = torch.load(str(path), map_location=device)
  File "G:\tj\anaconda\envs\gpu2\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "G:\tj\anaconda\envs\gpu2\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: synthesizer\saved_models\mandarin\ceshi.pt is a zip archive (did you mean to use torch.jit.load()?)

**Comment by ajunbudou** [comment]
继续点击合成出来都是杂音。

**Comment by babysor** [comment]
目前看跟pytorch版本有关 你的是哪个版本

**Comment by ajunbudou** [comment]
1.2.0

**Comment by XiuChen-Liu** [comment]
> 1.2.0

試試1.9.0?

**Comment by zky001** [comment]
> 

我在1.2.0也遇到了同样问题，1.8.0解决了
