### ISSUE TITLE
windows module 'umap' has no attribute 'UMAP'

### ISSUE THREAD

**Issue by heziyu2025** [babysor/MockingBird#805]
**Summary[问题简述（一句话）]**
在Windows上运行出现问题：module 'umap' has no attribute 'UMAP'
在训练声码器和启动demo时都出现了这个问题

**Env & To Reproduce[复现与环境]**
```
Traceback (most recent call last):
  File "D:\MockingBird\encoder_train.py", line 46, in <module>
    train(**vars(args))
  File "D:\MockingBird\encoder\train.py", line 100, in train
    vis.draw_projections(embeds, utterances_per_speaker, step, projection_fpath)
  File "D:\MockingBird\encoder\visualizations.py", line 164, in draw_projections
    reducer = umap.UMAP()
AttributeError: module 'umap' has no attribute 'UMAP'
```

**Comment by zky001** [comment]
同样遇到了这个问题

**Comment by HaSaKiYasuooo** [comment]
> 



> **Summary[问题简述（一句话）]** 在Windows上运行出现问题：module 'umap' has no attribute 'UMAP' 在训练声码器和启动demo时都出现了这个问题
> 
> **Env & To Reproduce[复现与环境]**
> 
> ```
> Traceback (most recent call last):
>   File "D:\MockingBird\encoder_train.py", line 46, in <module>
>     train(**vars(args))
>   File "D:\MockingBird\encoder\train.py", line 100, in train
>     vis.draw_projections(embeds, utterances_per_speaker, step, projection_fpath)
>   File "D:\MockingBird\encoder\visualizations.py", line 164, in draw_projections
>     reducer = umap.UMAP()
> AttributeError: module 'umap' has no attribute 'UMAP'
> ```

请问一下，如何解决这个问题，
