### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by aek791** [babysor/MockingBird#829]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-xs4mf_29\\monotonic-align_12ca82346dc54d988498a4d101b51b57\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-xs4mf_29\\monotonic-align_12ca82346dc54d988498a4d101b51b57\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-b36ghjqa'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-xs4mf_29\monotonic-align_12ca82346dc54d988498a4d101b51b57\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-xs4mf_29\monotonic-align_12ca82346dc54d988498a4d101b51b57\setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://mirrors.aliyun.com/pypi/packages/c4/35/4fc9f9a196990080bd27d22f4854110cbbbd5e411d9f5c6254ff569dc4d8/monotonic_align-0.0.3.tar.gz#sha256=9c4b09229895eb67ef9cac4cec30c42bc5af3bb297b13c0d0bf770ab7c3a7a94 (from https://mirrors.aliyun.com/pypi/simple/monotonic-align/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement monotonic-align==0.0.3 (from versions: 0.0.3)
ERROR: No matching distribution found for monotonic-align==0.0.3
WARNING: You are using pip version 21.2.4; however, version 23.0 is available.
You should consider upgrading via the 'C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

**Comment by babysor** [comment]
monotonic-align==0.0.3 这个可能阿里云镜像不存在，先设置为非阿里的试试

**Comment by runmouse** [comment]
> monotonic-align==0.0.3 这个可能阿里云镜像不存在，先设置为非阿里的试试

设置为豆瓣、清华的源都试过了，都不行。
能给一个源吗
