### ISSUE TITLE
web，可以启动，但是报了一个参数找不到，急

### ISSUE THREAD

**Issue by yangxiongj** [babysor/MockingBird#834]
023-02-21 21:11:04.315 INFO    numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-02-21 21:11:04.315 INFO    numexpr.utils: NumExpr defaulting to 8 threads.
  You can now view your Streamlit app in your browser.
  Network URL: http://192.168.30.102:8090
  External URL: http://218.74.20.181:8090
C:\Users\admin\anaconda3\envs\torch1.9\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
2023-02-21 21:11:09.685 Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\torch1.9\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\admin\AppData\Local\Temp\tmp9p7swpbm.py", line 13, in <module>
    render_streamlit_ui()
  File "C:\Users\admin\PycharmProjects\MockingBird\control\mkgui\base\ui\streamlit_ui.py", line 879, in render_streamlit_ui
    opyrator = getOpyrator(mode)
  File "C:\Users\admin\PycharmProjects\MockingBird\control\mkgui\base\ui\streamlit_ui.py", line 860, in getOpyrator
    from control.mkgui.app import synthesize
  File "C:\Users\admin\PycharmProjects\MockingBird\control\mkgui\app.py", line 31, in <module>
    synthesizers =  Enum('synthesizers', list((file.name, file) for file in Path(SYN_MODELS_DIRT).glob("**/*.pt")))
  File "C:\Users\admin\anaconda3\envs\torch1.9\lib\enum.py", line 341, in __call__
    return cls._create_(
  File "C:\Users\admin\anaconda3\envs\torch1.9\lib\enum.py", line 464, in _create_
    classdict[member_name] = member_value
  File "C:\Users\admin\anaconda3\envs\torch1.9\lib\enum.py", line 112, in __setitem__
    raise TypeError('Attempted to reuse key: %r' % key)
TypeError: Attempted to reuse key: 'pretrained.pt'

**Comment by StaryDreamer** [comment]
同问，不知道是不是模型没放好，不知道放哪里

**Comment by MaoSheng-super** [comment]
> 

模型是放在\MockingBird-main\data\ckpt\synthesizer下面的

**Comment by SoftCharacter** [comment]
找到"\MockingBird-main\data\ckpt\encoder"新建一个"saved_models"文件夹，把.pt文件放进去
