### ISSUE TITLE
Warning: you do not have any of the recognized datasets in samples

### ISSUE THREAD

**Issue by Candy0611** [babysor/MockingBird#882]
D:\MockingBird\MockingBird-main1>python demo_toolbox.py -d .\samples
Arguments:
    datasets_root:          samples
    vc_mode:                False
    enc_models_dir:         data\ckpt\encoder
    syn_models_dir:         data\ckpt\synthesizer
    voc_models_dir:         data\ckpt\vocoder
    extractor_models_dir:   data\ckpt\ppg_extractor
    convertor_models_dir:   data\ckpt\ppg2mel
    cpu:                    False
    seed:                   None
    no_mp3_support:         False

Warning: you do not have any of the recognized datasets in samples
Please note use 'E:\datasets' as root path instead of 'E:\datasetsidatatang_200zh\corpus        est' as an example .
The recognized datasets are:
        LibriSpeech/dev-clean
        LibriSpeech/dev-other
        LibriSpeech/test-clean
        LibriSpeech/test-other
        LibriSpeech/train-clean-100
        LibriSpeech/train-clean-360
        LibriSpeech/train-other-500
        LibriTTS/dev-clean
        LibriTTS/dev-other
        LibriTTS/test-clean
        LibriTTS/test-other
        LibriTTS/train-clean-100
        LibriTTS/train-clean-360
        LibriTTS/train-other-500
        LJSpeech-1.1
        VoxCeleb1/wav
        VoxCeleb1/test_wav
        VoxCeleb2/dev/aac
        VoxCeleb2/test/aac
        VCTK-Corpus/wav48
        aidatatang_200zh/corpus/test
        aidatatang_200zh/corpus/train
        aishell3/test/wav
        magicdata/train
Feel free to add your own. You can still use the toolbox by recording samples yourself.
Traceback (most recent call last):
  File "D:\MockingBird\MockingBird-main1\demo_toolbox.py", line 49, in <module>
    Toolbox(**vars(args))
  File "D:\MockingBird\MockingBird-main1\control\toolbox\__init__.py", line 80, in __init__
    self.reset_ui(enc_models_dir, syn_models_dir, voc_models_dir, extractor_models_dir, convertor_models_dir, seed)
  File "D:\MockingBird\MockingBird-main1\control\toolbox\__init__.py", line 162, in reset_ui
    self.ui.populate_models(encoder_models_dir, synthesizer_models_dir, vocoder_models_dir, extractor_models_dir, convertor_models_dir, self.vc_mode)
  File "D:\MockingBird\MockingBird-main1\control\toolbox\ui.py", line 362, in populate_models
    raise Exception("No synthesizer models found in %s" % synthesizer_models_dir)
Exception: No synthesizer models found in data\ckpt\synthesizer

**Comment by 111zhangsan** [comment]
![image](https://user-images.githubusercontent.com/132746201/236655556-8d61b6c0-40a3-4b80-8870-f8653de1cf55.png)
同问，问题解决了吗？

**Comment by zfm1997** [comment]
同样的问题，https://github.com/babysor/MockingBird/wiki/Quick-Start-(Newbie) ，wiki指导流程是否未及时更新，跟着操作下来报错

**Comment by wesfera** [comment]
@Candy0611 @111zhangsan @zfm1997 朋友们，按照提示，把pt模型文件放到 data/ckpt/synthesizer 目录下即可，没有目录就创建。应该可以解决
