### ISSUE TITLE
替换模型之后训练时报错

### ISSUE THREAD

**Issue by Maplexj** [babysor/MockingBird#890]
**Summary[问题简述（一句话）]**
A clear and concise description of what the issue is.
[替换模型之后训练时报错](url)
**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型
 python3.9  mockingbird0.0.1  75k模型
**Screenshots[截图（如有）]**
Arguments:
    run_id:          mandarin
    syn_dir:         F:/AI/mockingbird3/SV2TTS/synthesizer
    models_dir:      synthesizer/saved_models/
    save_every:      1000
    backup_every:    25000
    log_every:       200
    force_restart:   False
    hparams:

Checkpoint path: synthesizer\saved_models\mandarin\mandarin.pt
Loading training data from: F:\AI\mockingbird3\SV2TTS\synthesizer\train.txt
Using model: Tacotron
Using device: cuda

Initialising Tacotron Model...

Trainable Parameters: 30.875M

Loading weights at synthesizer\saved_models\mandarin\mandarin.pt
Traceback (most recent call last):
  File "F:\AI\mockingbird3\synthesizer_train.py", line 37, in <module>
    train(**vars(args))
  File "F:\AI\mockingbird3\synthesizer\train.py", line 114, in train
    model.load(weights_fpath, device, optimizer)
  File "F:\AI\mockingbird3\synthesizer\models\tacotron.py", line 550, in load
    optimizer.load_state_dict(checkpoint["optimizer_state"])
  File "F:\back\envs\mockingbrid\lib\site-packages\torch\optim\optimizer.py", line 390, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by HaSaKiYasuooo** [comment]
什么替换模型，没看懂
