### ISSUE TITLE
UnboundLocalError: local variable 'ppg' referenced before assignment

### ISSUE THREAD

**Issue by danfouer** [babysor/MockingBird#927]
**Summary[问题简述（一句话）]**
上传自己的wav文件报UnboundLocalError: local variable 'ppg' referenced before assignment

**Env & To Reproduce[复现与环境]**
描述你用的环境、代码版本、模型
Windows 10 ,python3.8 按照readme.txt安装成功 ，执行python demo_toolbox.py -vc -d "E:\3DData\sounddata\"
**Screenshots[截图（如有）]**
![image](https://github.com/babysor/MockingBird/assets/4875770/f4cc0748-86c0-477e-811c-5b0e80aa8438)
出错信息：
Traceback (most recent call last):
  File "E:\1JSONPro\MBIRD\control\toolbox\__init__.py", line 141, in <lambda>
    func = lambda: self.convert() or self.vocode()
  File "E:\1JSONPro\MBIRD\control\toolbox\__init__.py", line 378, in convert
    min_len = min(ppg.shape[1], len(lf0_uv))
UnboundLocalError: local variable 'ppg' referenced before assignment
Traceback (most recent call last):
  File "E:\1JSONPro\MBIRD\control\toolbox\__init__.py", line 141, in <lambda>
    func = lambda: self.convert() or self.vocode()
  File "E:\1JSONPro\MBIRD\control\toolbox\__init__.py", line 378, in convert
    min_len = min(ppg.shape[1], len(lf0_uv))
UnboundLocalError: local variable 'ppg' referenced before assignment
Traceback (most recent call last):
  File "E:\1JSONPro\MBIRD\control\toolbox\__init__.py", line 141, in <lambda>
    func = lambda: self.convert() or self.vocode()
  File "E:\1JSONPro\MBIRD\control\toolbox\__init__.py", line 378, in convert
    min_len = min(ppg.shape[1], len(lf0_uv))
UnboundLocalError: local variable 'ppg' referenced before assignment

**Comment by L1590** [comment]
Hello, I have the same problem as you, it seems that two models are not loaded, if you solve it, please help me, thank you very much!

**Comment by jimmyken** [comment]
这个怎么解决的?在M2上也会发生相同的错误.
