### ISSUE TITLE
运行pip install espnet安装失败

### ISSUE THREAD

**Issue by DrowskoytayhulGuider** [babysor/MockingBird#930]
在进行“4 语音转换”，准备环境时，运行pip install espnet来安装剩余必须的包时出错：
Collecting ctc-segmentation>=1.6.6
  Using cached ctc_segmentation-1.7.4.tar.gz (73 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\program files (x86)\python\python.exe' 'd:\program files (x86)\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\oydn\AppData\Local\Temp\pip-build-env-6kwlfgwz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools oldest-supported-numpy Cython
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "d:\program files (x86)\python\lib\runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "d:\program files (x86)\python\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "d:\program files (x86)\python\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "d:\program files (x86)\python\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "d:\program files (x86)\python\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "d:\program files (x86)\python\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 790, in exec_module
    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
    File "d:\program files (x86)\python\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "d:\program files (x86)\python\lib\site-packages\pip\_internal\cli\req_command.py", line 22, in <module>
      from pip._internal.req.constructors import (
    File "d:\program files (x86)\python\lib\site-packages\pip\_internal\req\__init__.py", line 10, in <module>
      from .req_install import InstallRequirement
    File "d:\program files (x86)\python\lib\site-packages\pip\_internal\req\req_install.py", line 10, in <module>
      import uuid
    File "d:\program files (x86)\python\lib\site-packages\uuid.py", line 138
      if not 0 <= time_low < 1<<32L:
                                  ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\program files (x86)\python\python.exe' 'd:\program files (x86)\python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\oydn\AppData\Local\Temp\pip-build-env-6kwlfgwz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools oldest-supported-numpy Cython Check the logs for full command output.
![Snipaste_2023-07-03_22-40-09](https://github.com/babysor/MockingBird/assets/77562801/1eced049-cdcf-489d-9984-06e13bad343d)

![Snipaste_2023-07-03_22-40-17](https://github.com/babysor/MockingBird/assets/77562801/0149f35d-98c7-4c08-9556-908df90a0678)

**Comment by 542002070112** [comment]
更新pip

**Comment by ZiQiuWang** [comment]
> 

+1
