### ISSUE TITLE
运行pre.py时报错如下，数据集的.npy文件没有生成导致的，但不知道是什么原因

### ISSUE THREAD

**Issue by DennisJcy** [babysor/MockingBird#958]
(torch12cu113) PS E:\project\MockingBird> python .\pre.py E:\project\MockingBird       
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Using data from:
    E:\project\MockingBird\aishell3\train\wav
aishell3:   0%|                                                                                                                     | 0/174 [00:00<?, ?speakers/s]Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
D:\Miniconda\envs\torch12cu113\lib\site-packages\librosa\util\decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
aishell3:   0%|                                                                                                                     | 0/174 [00:05<?, ?speakers/s] 
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\librosa\core\audio.py", line 164, in load
    y, sr_native = __soundfile_load(path, offset, duration, dtype)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\librosa\core\audio.py", line 195, in __soundfile_load
    context = sf.SoundFile(path)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'E:\\project\\MockingBird\\SV2TTS\\synthesizer\\audio\\audio-SSB00050001.wav_00.npy': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Miniconda\envs\torch12cu113\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "E:\project\MockingBird\models\synthesizer\preprocess_audio.py", line 124, in preprocess_general
    wav, text = _split_on_silences(wav_fpath, words, hparams)
  File "E:\project\MockingBird\models\synthesizer\preprocess_audio.py", line 88, in _split_on_silences
    wav, _ = librosa.load(wav_fpath, sr= hparams.sample_rate)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\librosa\util\decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\librosa\core\audio.py", line 170, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\librosa\core\audio.py", line 226, in __audioread_load
    reader = audioread.audio_open(path)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\audioread\rawread.py", line 59, in __init__
    self._fh = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\project\\MockingBird\\SV2TTS\\synthesizer\\audio\\audio-SSB00050001.wav_00.npy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\project\MockingBird\pre.py", line 72, in <module>
    preprocess_dataset(**vars(args))
  File "E:\project\MockingBird\models\synthesizer\preprocess.py", line 86, in preprocess_dataset
    for speaker_metadata in tqdm(job, dataset, len(speaker_dirs), unit="speakers"):
  File "D:\Miniconda\envs\torch12cu113\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\Miniconda\envs\torch12cu113\lib\multiprocessing\pool.py", line 870, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\project\\MockingBird\\SV2TTS\\synthesizer\\audio\\audio-SSB00050001.wav_00.npy'

**Comment by DennisJcy** [comment]
@babysor  您好，麻烦看下这个问题，我在Issue中没有找到相关的问题

**Comment by DennisJcy** [comment]
作者您好，您最新发布的pre.py应该是有bug，我用了旧的fock仓就可以正常跑

**Comment by SeaTidesPro** [comment]
看下linux的文档，在pre.py头部加入两行代码。

**Comment by DennisJcy** [comment]
感谢回复,明白你的意思,但我是win11下运行的 @SeaTidesPro

**Comment by JustDoItToo** [comment]
@DennisJcy 我也碰到了这个问题，困扰了一两天了，你解决了没有呀？

**Comment by JustDoItToo** [comment]
作者您好，您最新发布的pre.py应该是有bug，我用了旧的fock仓就可以正常跑
=>你是用哪个版本的仓库呀

**Comment by DennisJcy** [comment]
看下linux的文档,加上两行就行了

**Comment by JustDoItToo** [comment]
方便说下是哪个linux的文档吗？

**Comment by JustDoItToo** [comment]
@DennisJcy 方便告知下是哪个linux的文档吗？

**Comment by liulangdeyeshou** [comment]
> 看下linux的文档，加上两行就行了
你说的是这两行代码吧：
import torch
torch.multiprocessing.set_start_method('spawn', force=True)

我加上去以后还是报错，问题并未解决。

**Comment by liulangdeyeshou** [comment]
> 看下linux的文档,加上两行就行了


你说的是这两行代码吧：
import torch
torch.multiprocessing.set_start_method('spawn', force=True)

我加上去以后还是报错，问题并未解决。

**Comment by zzc-github** [comment]
> > 看下linux的文档,加上两行就行了
> 
> 你说的是这两行代码吧： import torch torch.multiprocessing.set_start_method('spawn', force=True)
> 
> 我加上去以后还是报错，问题并未解决。

我也报了这个错误，尽管我是WIN10专业版，也尝试在头部加了这两行代码，依然报版主上面的错误。
请问你解决了吗？

**Comment by zzc-github** [comment]
@liulangdeyeshou

**Comment by DennisJcy** [comment]
换旧版本吧

**Comment by huanglang0114** [comment]
解决了吗，我也遇到这个问题  Linux

**Comment by zzc-github** [comment]
> 解决了吗，我也遇到这个问题 Linux

@huanglang0114  linux 在pre.py头部+如下两行代码不行吗？
```
import torch
torch.multiprocessing.set_start_method('spawn', force=True)
```
我是Windows 加了不行，上面有大佬建议换其他分支，还没验证

**Comment by huanglang0114** [comment]
> > 解决了吗，我也遇到这个问题 Linux
> 
> @huanglang0114 linux 在pre.py头部+如下两行代码不行吗？
> 
> ```
> import torch
> torch.multiprocessing.set_start_method('spawn', force=True)
> ```
> 
> 我是Windows 加了不行，上面有大佬建议换其他分支，还没验证

不行   不知道啥原因   我在尝试用0.0.1那个分支了

**Comment by followdeep** [comment]
我解决了，希望对各位有帮助，原因是：preprocess_audio.py文件中的preprocess_general函数有问题 注意观察_split_on_silences和_process_utterance的具体参数内容，注意修改

**Comment by Danny0802** [comment]
> _process_utterance

请问具体要怎么改呢？

**Comment by Danny0802** [comment]
> @babysor 您好，麻烦看下这个问题，我在Issue中没有找到相关的问题

请问解决了吗？

**Comment by chiuhans111** [comment]
@Danny0802 , 我也遇到相同狀況，我嘗試了 #988  的 fix 之後問題解決了。
