### ISSUE TITLE
载入音频文件点synthesize and vocoder报如下错误

### ISSUE THREAD

**Issue by Godlikemandyy** [babysor/MockingBird#97]
`Traceback (most recent call last):
  File "D:\soft\MockingBird\toolbox\__init__.py", line 122, in <lambda>
    func = lambda: self.synthesize() or self.vocode()
  File "D:\soft\MockingBird\toolbox\__init__.py", line 236, in synthesize
    specs = self.synthesizer.synthesize_spectrograms(texts, embeds)
  File "D:\soft\MockingBird\synthesizer\inference.py", line 87, in synthesize_spectrograms
    self.load()
  File "D:\soft\MockingBird\synthesizer\inference.py", line 65, in load
    self._model.load(self.model_fpath)
  File "D:\soft\MockingBird\synthesizer\models\tacotron.py", line 497, in load
    self.load_state_dict(checkpoint["model_state"])
  File "D:\Anaconda3\envs\voice_cloning\lib\site-packages\torch\nn\modules\module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for encoder.embedding.weight: copying a param with shape torch.Size([70, 512]) from checkpoint, the shape in current model is torch.Size([75, 512]).`

torch==1.9.1
望各位大神指教！

**Comment by babysor** [comment]
参考 #37
